(define (problem logistics-p60)
	(:domain logistics)
	(:objects
		package-1 package-2 package-3 package-4 package-5 package-6 package-7 package-8 package-9 package-10 package-11 package-12 package-13 package-14 package-15 package-16 package-17 package-18 package-19 package-20 package-21 package-22 package-23 package-24 package-25 package-26 package-27 package-28 package-29 package-30 package-31 package-32 package-33 package-34 package-35 package-36 package-37 package-38 package-39 package-40 package-41 package-42 package-43 package-44 package-45 package-46 package-47 package-48 package-49 package-50 package-51 package-52 package-53 package-54 package-55 package-56 package-57 package-58 package-59 package-60 - package
		city-a city-b city-c - city
		truck-a truck-b truck-c - truck
		plane-1 plane-2 plane-3 - airplane
		house-a house-b house-c - location
		airport-a airport-b airport-c - location
		warehouse-a warehouse-b warehouse-c - location
	)
	(:init
		(AIRPORT airport-a)
		(AIRPORT airport-b)
		(AIRPORT airport-c)
		(in-city house-a city-a)
		(in-city airport-a city-a)
		(in-city warehouse-a city-a)
		(at plane-1 airport-a)
		(at truck-a warehouse-a)
		(in-city house-b city-b)
		(in-city airport-b city-b)
		(in-city warehouse-b city-b)
		(at plane-2 airport-b)
		(at truck-b warehouse-b)
		(in-city house-c city-c)
		(in-city airport-c city-c)
		(in-city warehouse-c city-c)
		(at plane-3 airport-c)
		(at truck-c warehouse-c)
		(at package-1 warehouse-a)
		(at package-2 warehouse-b)
		(at package-3 warehouse-c)
		(at package-4 warehouse-a)
		(at package-5 warehouse-b)
		(at package-6 warehouse-c)
		(at package-7 warehouse-a)
		(at package-8 warehouse-b)
		(at package-9 warehouse-c)
		(at package-10 warehouse-a)
		(at package-11 warehouse-b)
		(at package-12 warehouse-c)
		(at package-13 warehouse-a)
		(at package-14 warehouse-b)
		(at package-15 warehouse-c)
		(at package-16 warehouse-a)
		(at package-17 warehouse-b)
		(at package-18 warehouse-c)
		(at package-19 warehouse-a)
		(at package-20 warehouse-b)
		(at package-21 warehouse-c)
		(at package-22 warehouse-a)
		(at package-23 warehouse-b)
		(at package-24 warehouse-c)
		(at package-25 warehouse-a)
		(at package-26 warehouse-b)
		(at package-27 warehouse-c)
		(at package-28 warehouse-a)
		(at package-29 warehouse-b)
		(at package-30 warehouse-c)
		(at package-31 warehouse-a)
		(at package-32 warehouse-b)
		(at package-33 warehouse-c)
		(at package-34 warehouse-a)
		(at package-35 warehouse-b)
		(at package-36 warehouse-c)
		(at package-37 warehouse-a)
		(at package-38 warehouse-b)
		(at package-39 warehouse-c)
		(at package-40 warehouse-a)
		(at package-41 warehouse-b)
		(at package-42 warehouse-c)
		(at package-43 warehouse-a)
		(at package-44 warehouse-b)
		(at package-45 warehouse-c)
		(at package-46 warehouse-a)
		(at package-47 warehouse-b)
		(at package-48 warehouse-c)
		(at package-49 warehouse-a)
		(at package-50 warehouse-b)
		(at package-51 warehouse-c)
		(at package-52 warehouse-a)
		(at package-53 warehouse-b)
		(at package-54 warehouse-c)
		(at package-55 warehouse-a)
		(at package-56 warehouse-b)
		(at package-57 warehouse-c)
		(at package-58 warehouse-a)
		(at package-59 warehouse-b)
		(at package-60 warehouse-c)
	)
	(:goal (and
		(at package-1 house-b)
		(at package-2 house-c)
		(at package-3 house-a)
		(at package-4 house-b)
		(at package-5 house-c)
		(at package-6 house-a)
		(at package-7 house-b)
		(at package-8 house-c)
		(at package-9 house-a)
		(at package-10 house-b)
		(at package-11 house-c)
		(at package-12 house-a)
		(at package-13 house-b)
		(at package-14 house-c)
		(at package-15 house-a)
		(at package-16 house-b)
		(at package-17 house-c)
		(at package-18 house-a)
		(at package-19 house-b)
		(at package-20 house-c)
		(at package-21 house-a)
		(at package-22 house-b)
		(at package-23 house-c)
		(at package-24 house-a)
		(at package-25 house-b)
		(at package-26 house-c)
		(at package-27 house-a)
		(at package-28 house-b)
		(at package-29 house-c)
		(at package-30 house-a)
		(at package-31 house-b)
		(at package-32 house-c)
		(at package-33 house-a)
		(at package-34 house-b)
		(at package-35 house-c)
		(at package-36 house-a)
		(at package-37 house-b)
		(at package-38 house-c)
		(at package-39 house-a)
		(at package-40 house-b)
		(at package-41 house-c)
		(at package-42 house-a)
		(at package-43 house-b)
		(at package-44 house-c)
		(at package-45 house-a)
		(at package-46 house-b)
		(at package-47 house-c)
		(at package-48 house-a)
		(at package-49 house-b)
		(at package-50 house-c)
		(at package-51 house-a)
		(at package-52 house-b)
		(at package-53 house-c)
		(at package-54 house-a)
		(at package-55 house-b)
		(at package-56 house-c)
		(at package-57 house-a)
		(at package-58 house-b)
		(at package-59 house-c)
		(at package-60 house-a)
		)
	)
)
