(define (problem logistics-p1)
	(:domain logistics)
	(:objects
		package-1
		city-a city-b city-c
		truck-a truck-b truck-c
		plane-1 plane-2 plane-3
		house-a house-b house-c
		airport-a airport-b airport-c
		warehouse-a warehouse-b warehouse-c
	)
	(:init
		(PACKAGE package-1)
		(CITY city-a)
		(CITY city-b)
		(CITY city-c)
		(TRUCK truck-a)
		(TRUCK truck-b)
		(TRUCK truck-c)
		(AIRPLANE plane-1)
		(AIRPLANE plane-2)
		(AIRPLANE plane-3)
		(LOCATION house-a)
		(LOCATION house-b)
		(LOCATION house-c)
		(LOCATION airport-a)
		(LOCATION airport-b)
		(LOCATION airport-c)
		(LOCATION warehouse-a)
		(LOCATION warehouse-b)
		(LOCATION warehouse-c)
		(AIRPORT airport-a)
		(AIRPORT airport-b)
		(AIRPORT airport-c)
		(in-city house-a city-a)
		(in-city airport-a city-a)
		(in-city warehouse-a city-a)
		(at plane-1 airport-a)
		(at truck-a warehouse-a)
		(in-city house-b city-b)
		(in-city airport-b city-b)
		(in-city warehouse-b city-b)
		(at plane-2 airport-b)
		(at truck-b warehouse-b)
		(in-city house-c city-c)
		(in-city airport-c city-c)
		(in-city warehouse-c city-c)
		(at plane-3 airport-c)
		(at truck-c warehouse-c)
		(at package-1 warehouse-a)
	)
	(:goal (and
		(at package-1 house-b)
		)
	)
)
