(define (problem hamburger-strips-p10-r1)
	(:domain hamburger-strips)
	(:objects
		lettuce-1 lettuce-2 lettuce-3 lettuce-4 lettuce-5 lettuce-6 lettuce-7 lettuce-8 lettuce-9 lettuce-10
		buns-1 buns-2 buns-3 buns-4 buns-5 buns-6 buns-7 buns-8 buns-9 buns-10
		meat-1 meat-2 meat-3 meat-4 meat-5 meat-6 meat-7 meat-8 meat-9 meat-10
		plate-1 plate-2 plate-3 plate-4 plate-5 plate-6 plate-7 plate-8 plate-9 plate-10
		robot-1
		robot-loc buns-loc lettuce-loc meat-loc plate-loc
	)
	(:init
		(LOCATION robot-loc)
		(LOCATION buns-loc)
		(LOCATION lettuce-loc)
		(LOCATION meat-loc)
		(LOCATION plate-loc)
		(ROBOT robot-1)
		(BUNS buns-1)
		(BUNS buns-2)
		(BUNS buns-3)
		(BUNS buns-4)
		(BUNS buns-5)
		(BUNS buns-6)
		(BUNS buns-7)
		(BUNS buns-8)
		(BUNS buns-9)
		(BUNS buns-10)
		(LETTUCE lettuce-1)
		(LETTUCE lettuce-2)
		(LETTUCE lettuce-3)
		(LETTUCE lettuce-4)
		(LETTUCE lettuce-5)
		(LETTUCE lettuce-6)
		(LETTUCE lettuce-7)
		(LETTUCE lettuce-8)
		(LETTUCE lettuce-9)
		(LETTUCE lettuce-10)
		(MEAT meat-1)
		(MEAT meat-2)
		(MEAT meat-3)
		(MEAT meat-4)
		(MEAT meat-5)
		(MEAT meat-6)
		(MEAT meat-7)
		(MEAT meat-8)
		(MEAT meat-9)
		(MEAT meat-10)
		(PLATE plate-1)
		(PLATE plate-2)
		(PLATE plate-3)
		(PLATE plate-4)
		(PLATE plate-5)
		(PLATE plate-6)
		(PLATE plate-7)
		(PLATE plate-8)
		(PLATE plate-9)
		(PLATE plate-10)
		(at robot-1 robot-loc)
		(at buns-1 buns-loc)
		(at buns-2 buns-loc)
		(at buns-3 buns-loc)
		(at buns-4 buns-loc)
		(at buns-5 buns-loc)
		(at buns-6 buns-loc)
		(at buns-7 buns-loc)
		(at buns-8 buns-loc)
		(at buns-9 buns-loc)
		(at buns-10 buns-loc)
		(at lettuce-1 lettuce-loc)
		(at lettuce-2 lettuce-loc)
		(at lettuce-3 lettuce-loc)
		(at lettuce-4 lettuce-loc)
		(at lettuce-5 lettuce-loc)
		(at lettuce-6 lettuce-loc)
		(at lettuce-7 lettuce-loc)
		(at lettuce-8 lettuce-loc)
		(at lettuce-9 lettuce-loc)
		(at lettuce-10 lettuce-loc)
		(at meat-1 meat-loc)
		(at meat-2 meat-loc)
		(at meat-3 meat-loc)
		(at meat-4 meat-loc)
		(at meat-5 meat-loc)
		(at meat-6 meat-loc)
		(at meat-7 meat-loc)
		(at meat-8 meat-loc)
		(at meat-9 meat-loc)
		(at meat-10 meat-loc)
		(at plate-1 plate-loc)
		(at plate-2 plate-loc)
		(at plate-3 plate-loc)
		(at plate-4 plate-loc)
		(at plate-5 plate-loc)
		(at plate-6 plate-loc)
		(at plate-7 plate-loc)
		(at plate-8 plate-loc)
		(at plate-9 plate-loc)
		(at plate-10 plate-loc)
		(no-burger plate-1)
		(no-buns plate-1)
		(no-lettuce plate-1)
		(no-meat plate-1)
		(no-burger plate-2)
		(no-buns plate-2)
		(no-lettuce plate-2)
		(no-meat plate-2)
		(no-burger plate-3)
		(no-buns plate-3)
		(no-lettuce plate-3)
		(no-meat plate-3)
		(no-burger plate-4)
		(no-buns plate-4)
		(no-lettuce plate-4)
		(no-meat plate-4)
		(no-burger plate-5)
		(no-buns plate-5)
		(no-lettuce plate-5)
		(no-meat plate-5)
		(no-burger plate-6)
		(no-buns plate-6)
		(no-lettuce plate-6)
		(no-meat plate-6)
		(no-burger plate-7)
		(no-buns plate-7)
		(no-lettuce plate-7)
		(no-meat plate-7)
		(no-burger plate-8)
		(no-buns plate-8)
		(no-lettuce plate-8)
		(no-meat plate-8)
		(no-burger plate-9)
		(no-buns plate-9)
		(no-lettuce plate-9)
		(no-meat plate-9)
		(no-burger plate-10)
		(no-buns plate-10)
		(no-lettuce plate-10)
		(no-meat plate-10)
		(empty-hand robot-1)
	)
	(:goal (and
		(have-burger plate-1)
		(have-burger plate-2)
		(have-burger plate-3)
		(have-burger plate-4)
		(have-burger plate-5)
		(have-burger plate-6)
		(have-burger plate-7)
		(have-burger plate-8)
		(have-burger plate-9)
		(have-burger plate-10)
		)
	)
)
