(define (problem restaurant-strips-s1-c50)
	(:domain restaurant-strips)
	(:objects
		customer-1 customer-2 customer-3 customer-4 customer-5 customer-6 customer-7 customer-8 customer-9 customer-10 customer-11 customer-12 customer-13 customer-14 customer-15 customer-16 customer-17 customer-18 customer-19 customer-20 customer-21 customer-22 customer-23 customer-24 customer-25 customer-26 customer-27 customer-28 customer-29 customer-30 customer-31 customer-32 customer-33 customer-34 customer-35 customer-36 customer-37 customer-38 customer-39 customer-40 customer-41 customer-42 customer-43 customer-44 customer-45 customer-46 customer-47 customer-48 customer-49 customer-50
		server-1
		dough-1 dough-2 dough-3 dough-4 dough-5 dough-6 dough-7 dough-8 dough-9 dough-10 dough-11 dough-12 dough-13 dough-14 dough-15 dough-16
		toppings-1 toppings-2 toppings-3 toppings-4 toppings-5 toppings-6 toppings-7 toppings-8 toppings-9 toppings-10 toppings-11 toppings-12 toppings-13 toppings-14 toppings-15 toppings-16
		cheese-1 cheese-2 cheese-3 cheese-4 cheese-5 cheese-6 cheese-7 cheese-8 cheese-9 cheese-10 cheese-11 cheese-12 cheese-13 cheese-14 cheese-15 cheese-16
		potato-1 potato-2 potato-3 potato-4 potato-5 potato-6 potato-7 potato-8 potato-9 potato-10 potato-11 potato-12 potato-13 potato-14 potato-15 potato-16 potato-17 potato-18 potato-19 potato-20 potato-21 potato-22 potato-23 potato-24 potato-25 potato-26 potato-27 potato-28 potato-29 potato-30 potato-31 potato-32 potato-33 potato-34
		fries-1 fries-2 fries-3 fries-4 fries-5 fries-6 fries-7 fries-8 fries-9 fries-10 fries-11 fries-12 fries-13 fries-14 fries-15 fries-16 fries-17 fries-18 fries-19 fries-20 fries-21 fries-22 fries-23 fries-24 fries-25 fries-26 fries-27 fries-28 fries-29 fries-30 fries-31 fries-32 fries-33 fries-34
		pizza-1 pizza-2 pizza-3 pizza-4 pizza-5 pizza-6 pizza-7 pizza-8 pizza-9 pizza-10 pizza-11 pizza-12 pizza-13 pizza-14 pizza-15 pizza-16
		kitchen table bar
	)
	(:init
		(LOCATION kitchen)
		(LOCATION table)
		(LOCATION bar)
		(CUSTOMER customer-1)
		(CUSTOMER customer-2)
		(CUSTOMER customer-3)
		(CUSTOMER customer-4)
		(CUSTOMER customer-5)
		(CUSTOMER customer-6)
		(CUSTOMER customer-7)
		(CUSTOMER customer-8)
		(CUSTOMER customer-9)
		(CUSTOMER customer-10)
		(CUSTOMER customer-11)
		(CUSTOMER customer-12)
		(CUSTOMER customer-13)
		(CUSTOMER customer-14)
		(CUSTOMER customer-15)
		(CUSTOMER customer-16)
		(CUSTOMER customer-17)
		(CUSTOMER customer-18)
		(CUSTOMER customer-19)
		(CUSTOMER customer-20)
		(CUSTOMER customer-21)
		(CUSTOMER customer-22)
		(CUSTOMER customer-23)
		(CUSTOMER customer-24)
		(CUSTOMER customer-25)
		(CUSTOMER customer-26)
		(CUSTOMER customer-27)
		(CUSTOMER customer-28)
		(CUSTOMER customer-29)
		(CUSTOMER customer-30)
		(CUSTOMER customer-31)
		(CUSTOMER customer-32)
		(CUSTOMER customer-33)
		(CUSTOMER customer-34)
		(CUSTOMER customer-35)
		(CUSTOMER customer-36)
		(CUSTOMER customer-37)
		(CUSTOMER customer-38)
		(CUSTOMER customer-39)
		(CUSTOMER customer-40)
		(CUSTOMER customer-41)
		(CUSTOMER customer-42)
		(CUSTOMER customer-43)
		(CUSTOMER customer-44)
		(CUSTOMER customer-45)
		(CUSTOMER customer-46)
		(CUSTOMER customer-47)
		(CUSTOMER customer-48)
		(CUSTOMER customer-49)
		(CUSTOMER customer-50)
		(SERVER server-1)
		(DOUGH dough-1)
		(DOUGH dough-2)
		(DOUGH dough-3)
		(DOUGH dough-4)
		(DOUGH dough-5)
		(DOUGH dough-6)
		(DOUGH dough-7)
		(DOUGH dough-8)
		(DOUGH dough-9)
		(DOUGH dough-10)
		(DOUGH dough-11)
		(DOUGH dough-12)
		(DOUGH dough-13)
		(DOUGH dough-14)
		(DOUGH dough-15)
		(DOUGH dough-16)
		(TOPPINGS toppings-1)
		(TOPPINGS toppings-2)
		(TOPPINGS toppings-3)
		(TOPPINGS toppings-4)
		(TOPPINGS toppings-5)
		(TOPPINGS toppings-6)
		(TOPPINGS toppings-7)
		(TOPPINGS toppings-8)
		(TOPPINGS toppings-9)
		(TOPPINGS toppings-10)
		(TOPPINGS toppings-11)
		(TOPPINGS toppings-12)
		(TOPPINGS toppings-13)
		(TOPPINGS toppings-14)
		(TOPPINGS toppings-15)
		(TOPPINGS toppings-16)
		(CHEESE cheese-1)
		(CHEESE cheese-2)
		(CHEESE cheese-3)
		(CHEESE cheese-4)
		(CHEESE cheese-5)
		(CHEESE cheese-6)
		(CHEESE cheese-7)
		(CHEESE cheese-8)
		(CHEESE cheese-9)
		(CHEESE cheese-10)
		(CHEESE cheese-11)
		(CHEESE cheese-12)
		(CHEESE cheese-13)
		(CHEESE cheese-14)
		(CHEESE cheese-15)
		(CHEESE cheese-16)
		(POTATO potato-1)
		(POTATO potato-2)
		(POTATO potato-3)
		(POTATO potato-4)
		(POTATO potato-5)
		(POTATO potato-6)
		(POTATO potato-7)
		(POTATO potato-8)
		(POTATO potato-9)
		(POTATO potato-10)
		(POTATO potato-11)
		(POTATO potato-12)
		(POTATO potato-13)
		(POTATO potato-14)
		(POTATO potato-15)
		(POTATO potato-16)
		(POTATO potato-17)
		(POTATO potato-18)
		(POTATO potato-19)
		(POTATO potato-20)
		(POTATO potato-21)
		(POTATO potato-22)
		(POTATO potato-23)
		(POTATO potato-24)
		(POTATO potato-25)
		(POTATO potato-26)
		(POTATO potato-27)
		(POTATO potato-28)
		(POTATO potato-29)
		(POTATO potato-30)
		(POTATO potato-31)
		(POTATO potato-32)
		(POTATO potato-33)
		(POTATO potato-34)
		(PIZZA pizza-1)
		(PIZZA pizza-2)
		(PIZZA pizza-3)
		(PIZZA pizza-4)
		(PIZZA pizza-5)
		(PIZZA pizza-6)
		(PIZZA pizza-7)
		(PIZZA pizza-8)
		(PIZZA pizza-9)
		(PIZZA pizza-10)
		(PIZZA pizza-11)
		(PIZZA pizza-12)
		(PIZZA pizza-13)
		(PIZZA pizza-14)
		(PIZZA pizza-15)
		(PIZZA pizza-16)
		(FRIES fries-1)
		(FRIES fries-2)
		(FRIES fries-3)
		(FRIES fries-4)
		(FRIES fries-5)
		(FRIES fries-6)
		(FRIES fries-7)
		(FRIES fries-8)
		(FRIES fries-9)
		(FRIES fries-10)
		(FRIES fries-11)
		(FRIES fries-12)
		(FRIES fries-13)
		(FRIES fries-14)
		(FRIES fries-15)
		(FRIES fries-16)
		(FRIES fries-17)
		(FRIES fries-18)
		(FRIES fries-19)
		(FRIES fries-20)
		(FRIES fries-21)
		(FRIES fries-22)
		(FRIES fries-23)
		(FRIES fries-24)
		(FRIES fries-25)
		(FRIES fries-26)
		(FRIES fries-27)
		(FRIES fries-28)
		(FRIES fries-29)
		(FRIES fries-30)
		(FRIES fries-31)
		(FRIES fries-32)
		(FRIES fries-33)
		(FRIES fries-34)
		(waiting-at customer-1 table)
		(ordered-pizza customer-1)
		(waiting-at customer-2 table)
		(ordered-pizza customer-2)
		(waiting-at customer-3 table)
		(ordered-pizza customer-3)
		(waiting-at customer-4 table)
		(ordered-pizza customer-4)
		(waiting-at customer-5 bar)
		(ordered-pizza customer-5)
		(waiting-at customer-6 table)
		(ordered-pizza customer-6)
		(waiting-at customer-7 table)
		(ordered-pizza customer-7)
		(waiting-at customer-8 table)
		(ordered-pizza customer-8)
		(waiting-at customer-9 table)
		(ordered-pizza customer-9)
		(waiting-at customer-10 bar)
		(ordered-pizza customer-10)
		(waiting-at customer-11 table)
		(ordered-pizza customer-11)
		(waiting-at customer-12 table)
		(ordered-pizza customer-12)
		(waiting-at customer-13 table)
		(ordered-pizza customer-13)
		(waiting-at customer-14 table)
		(ordered-pizza customer-14)
		(waiting-at customer-15 table)
		(ordered-pizza customer-15)
		(waiting-at customer-16 bar)
		(ordered-pizza customer-16)
		(waiting-at customer-17 bar)
		(ordered-fries customer-17)
		(waiting-at customer-18 table)
		(ordered-fries customer-18)
		(waiting-at customer-19 table)
		(ordered-fries customer-19)
		(waiting-at customer-20 bar)
		(ordered-fries customer-20)
		(waiting-at customer-21 bar)
		(ordered-fries customer-21)
		(waiting-at customer-22 bar)
		(ordered-fries customer-22)
		(waiting-at customer-23 table)
		(ordered-fries customer-23)
		(waiting-at customer-24 bar)
		(ordered-fries customer-24)
		(waiting-at customer-25 table)
		(ordered-fries customer-25)
		(waiting-at customer-26 bar)
		(ordered-fries customer-26)
		(waiting-at customer-27 table)
		(ordered-fries customer-27)
		(waiting-at customer-28 bar)
		(ordered-fries customer-28)
		(waiting-at customer-29 table)
		(ordered-fries customer-29)
		(waiting-at customer-30 table)
		(ordered-fries customer-30)
		(waiting-at customer-31 bar)
		(ordered-fries customer-31)
		(waiting-at customer-32 table)
		(ordered-fries customer-32)
		(waiting-at customer-33 table)
		(ordered-fries customer-33)
		(waiting-at customer-34 table)
		(ordered-fries customer-34)
		(waiting-at customer-35 bar)
		(ordered-fries customer-35)
		(waiting-at customer-36 bar)
		(ordered-fries customer-36)
		(waiting-at customer-37 table)
		(ordered-fries customer-37)
		(waiting-at customer-38 bar)
		(ordered-fries customer-38)
		(waiting-at customer-39 bar)
		(ordered-fries customer-39)
		(waiting-at customer-40 bar)
		(ordered-fries customer-40)
		(waiting-at customer-41 bar)
		(ordered-fries customer-41)
		(waiting-at customer-42 table)
		(ordered-fries customer-42)
		(waiting-at customer-43 bar)
		(ordered-fries customer-43)
		(waiting-at customer-44 bar)
		(ordered-fries customer-44)
		(waiting-at customer-45 table)
		(ordered-fries customer-45)
		(waiting-at customer-46 table)
		(ordered-fries customer-46)
		(waiting-at customer-47 table)
		(ordered-fries customer-47)
		(waiting-at customer-48 bar)
		(ordered-fries customer-48)
		(waiting-at customer-49 table)
		(ordered-fries customer-49)
		(waiting-at customer-50 bar)
		(ordered-fries customer-50)
		(at server-1 kitchen)
		(empty-hand server-1)
		(at dough-1 kitchen)
		(at dough-2 kitchen)
		(at dough-3 kitchen)
		(at dough-4 kitchen)
		(at dough-5 kitchen)
		(at dough-6 kitchen)
		(at dough-7 kitchen)
		(at dough-8 kitchen)
		(at dough-9 kitchen)
		(at dough-10 kitchen)
		(at dough-11 kitchen)
		(at dough-12 kitchen)
		(at dough-13 kitchen)
		(at dough-14 kitchen)
		(at dough-15 kitchen)
		(at dough-16 kitchen)
		(at toppings-1 kitchen)
		(at toppings-2 kitchen)
		(at toppings-3 kitchen)
		(at toppings-4 kitchen)
		(at toppings-5 kitchen)
		(at toppings-6 kitchen)
		(at toppings-7 kitchen)
		(at toppings-8 kitchen)
		(at toppings-9 kitchen)
		(at toppings-10 kitchen)
		(at toppings-11 kitchen)
		(at toppings-12 kitchen)
		(at toppings-13 kitchen)
		(at toppings-14 kitchen)
		(at toppings-15 kitchen)
		(at toppings-16 kitchen)
		(at cheese-1 kitchen)
		(at cheese-2 kitchen)
		(at cheese-3 kitchen)
		(at cheese-4 kitchen)
		(at cheese-5 kitchen)
		(at cheese-6 kitchen)
		(at cheese-7 kitchen)
		(at cheese-8 kitchen)
		(at cheese-9 kitchen)
		(at cheese-10 kitchen)
		(at cheese-11 kitchen)
		(at cheese-12 kitchen)
		(at cheese-13 kitchen)
		(at cheese-14 kitchen)
		(at cheese-15 kitchen)
		(at cheese-16 kitchen)
		(at potato-1 kitchen)
		(at potato-2 kitchen)
		(at potato-3 kitchen)
		(at potato-4 kitchen)
		(at potato-5 kitchen)
		(at potato-6 kitchen)
		(at potato-7 kitchen)
		(at potato-8 kitchen)
		(at potato-9 kitchen)
		(at potato-10 kitchen)
		(at potato-11 kitchen)
		(at potato-12 kitchen)
		(at potato-13 kitchen)
		(at potato-14 kitchen)
		(at potato-15 kitchen)
		(at potato-16 kitchen)
		(at potato-17 kitchen)
		(at potato-18 kitchen)
		(at potato-19 kitchen)
		(at potato-20 kitchen)
		(at potato-21 kitchen)
		(at potato-22 kitchen)
		(at potato-23 kitchen)
		(at potato-24 kitchen)
		(at potato-25 kitchen)
		(at potato-26 kitchen)
		(at potato-27 kitchen)
		(at potato-28 kitchen)
		(at potato-29 kitchen)
		(at potato-30 kitchen)
		(at potato-31 kitchen)
		(at potato-32 kitchen)
		(at potato-33 kitchen)
		(at potato-34 kitchen)
		(full-potato potato-1)
		(full-potato potato-2)
		(full-potato potato-3)
		(full-potato potato-4)
		(full-potato potato-5)
		(full-potato potato-6)
		(full-potato potato-7)
		(full-potato potato-8)
		(full-potato potato-9)
		(full-potato potato-10)
		(full-potato potato-11)
		(full-potato potato-12)
		(full-potato potato-13)
		(full-potato potato-14)
		(full-potato potato-15)
		(full-potato potato-16)
		(full-potato potato-17)
		(full-potato potato-18)
		(full-potato potato-19)
		(full-potato potato-20)
		(full-potato potato-21)
		(full-potato potato-22)
		(full-potato potato-23)
		(full-potato potato-24)
		(full-potato potato-25)
		(full-potato potato-26)
		(full-potato potato-27)
		(full-potato potato-28)
		(full-potato potato-29)
		(full-potato potato-30)
		(full-potato potato-31)
		(full-potato potato-32)
		(full-potato potato-33)
		(full-potato potato-34)
		(no-exist-pizza pizza-1)
		(no-exist-pizza pizza-2)
		(no-exist-pizza pizza-3)
		(no-exist-pizza pizza-4)
		(no-exist-pizza pizza-5)
		(no-exist-pizza pizza-6)
		(no-exist-pizza pizza-7)
		(no-exist-pizza pizza-8)
		(no-exist-pizza pizza-9)
		(no-exist-pizza pizza-10)
		(no-exist-pizza pizza-11)
		(no-exist-pizza pizza-12)
		(no-exist-pizza pizza-13)
		(no-exist-pizza pizza-14)
		(no-exist-pizza pizza-15)
		(no-exist-pizza pizza-16)
		(no-exist-fries fries-1)
		(no-exist-fries fries-2)
		(no-exist-fries fries-3)
		(no-exist-fries fries-4)
		(no-exist-fries fries-5)
		(no-exist-fries fries-6)
		(no-exist-fries fries-7)
		(no-exist-fries fries-8)
		(no-exist-fries fries-9)
		(no-exist-fries fries-10)
		(no-exist-fries fries-11)
		(no-exist-fries fries-12)
		(no-exist-fries fries-13)
		(no-exist-fries fries-14)
		(no-exist-fries fries-15)
		(no-exist-fries fries-16)
		(no-exist-fries fries-17)
		(no-exist-fries fries-18)
		(no-exist-fries fries-19)
		(no-exist-fries fries-20)
		(no-exist-fries fries-21)
		(no-exist-fries fries-22)
		(no-exist-fries fries-23)
		(no-exist-fries fries-24)
		(no-exist-fries fries-25)
		(no-exist-fries fries-26)
		(no-exist-fries fries-27)
		(no-exist-fries fries-28)
		(no-exist-fries fries-29)
		(no-exist-fries fries-30)
		(no-exist-fries fries-31)
		(no-exist-fries fries-32)
		(no-exist-fries fries-33)
		(no-exist-fries fries-34)
	)
	(:goal (and
		(served customer-1)
		(served customer-2)
		(served customer-3)
		(served customer-4)
		(served customer-5)
		(served customer-6)
		(served customer-7)
		(served customer-8)
		(served customer-9)
		(served customer-10)
		(served customer-11)
		(served customer-12)
		(served customer-13)
		(served customer-14)
		(served customer-15)
		(served customer-16)
		(served customer-17)
		(served customer-18)
		(served customer-19)
		(served customer-20)
		(served customer-21)
		(served customer-22)
		(served customer-23)
		(served customer-24)
		(served customer-25)
		(served customer-26)
		(served customer-27)
		(served customer-28)
		(served customer-29)
		(served customer-30)
		(served customer-31)
		(served customer-32)
		(served customer-33)
		(served customer-34)
		(served customer-35)
		(served customer-36)
		(served customer-37)
		(served customer-38)
		(served customer-39)
		(served customer-40)
		(served customer-41)
		(served customer-42)
		(served customer-43)
		(served customer-44)
		(served customer-45)
		(served customer-46)
		(served customer-47)
		(served customer-48)
		(served customer-49)
		(served customer-50)
		)
	)
)
