(define (problem restaurant-strips-s1-c7)
	(:domain restaurant-strips)
	(:objects
		customer-1 customer-2 customer-3 customer-4 customer-5 customer-6 customer-7
		server-1
		
		
		
		potato-1 potato-2 potato-3 potato-4 potato-5 potato-6 potato-7
		fries-1 fries-2 fries-3 fries-4 fries-5 fries-6 fries-7
		
		kitchen table bar
	)
	(:init
		(LOCATION kitchen)
		(LOCATION table)
		(LOCATION bar)
		(CUSTOMER customer-1)
		(CUSTOMER customer-2)
		(CUSTOMER customer-3)
		(CUSTOMER customer-4)
		(CUSTOMER customer-5)
		(CUSTOMER customer-6)
		(CUSTOMER customer-7)
		(SERVER server-1)
		(POTATO potato-1)
		(POTATO potato-2)
		(POTATO potato-3)
		(POTATO potato-4)
		(POTATO potato-5)
		(POTATO potato-6)
		(POTATO potato-7)
		(FRIES fries-1)
		(FRIES fries-2)
		(FRIES fries-3)
		(FRIES fries-4)
		(FRIES fries-5)
		(FRIES fries-6)
		(FRIES fries-7)
		(waiting-at customer-1 bar)
		(ordered-fries customer-1)
		(waiting-at customer-2 bar)
		(ordered-fries customer-2)
		(waiting-at customer-3 bar)
		(ordered-fries customer-3)
		(waiting-at customer-4 bar)
		(ordered-fries customer-4)
		(waiting-at customer-5 table)
		(ordered-fries customer-5)
		(waiting-at customer-6 table)
		(ordered-fries customer-6)
		(waiting-at customer-7 table)
		(ordered-fries customer-7)
		(at server-1 kitchen)
		(empty-hand server-1)
		(at potato-1 kitchen)
		(at potato-2 kitchen)
		(at potato-3 kitchen)
		(at potato-4 kitchen)
		(at potato-5 kitchen)
		(at potato-6 kitchen)
		(at potato-7 kitchen)
		(full-potato potato-1)
		(full-potato potato-2)
		(full-potato potato-3)
		(full-potato potato-4)
		(full-potato potato-5)
		(full-potato potato-6)
		(full-potato potato-7)
		(no-exist-fries fries-1)
		(no-exist-fries fries-2)
		(no-exist-fries fries-3)
		(no-exist-fries fries-4)
		(no-exist-fries fries-5)
		(no-exist-fries fries-6)
		(no-exist-fries fries-7)
	)
	(:goal (and
		(served customer-1)
		(served customer-2)
		(served customer-3)
		(served customer-4)
		(served customer-5)
		(served customer-6)
		(served customer-7)
		)
	)
)
