(define (problem restaurant-strips-s1-c50)
	(:domain restaurant-strips)
	(:objects
		customer-1 customer-2 customer-3 customer-4 customer-5 customer-6 customer-7 customer-8 customer-9 customer-10 customer-11 customer-12 customer-13 customer-14 customer-15 customer-16 customer-17 customer-18 customer-19 customer-20 customer-21 customer-22 customer-23 customer-24 customer-25 customer-26 customer-27 customer-28 customer-29 customer-30 customer-31 customer-32 customer-33 customer-34 customer-35 customer-36 customer-37 customer-38 customer-39 customer-40 customer-41 customer-42 customer-43 customer-44 customer-45 customer-46 customer-47 customer-48 customer-49 customer-50
		server-1
		dough-1 dough-2 dough-3 dough-4 dough-5 dough-6 dough-7 dough-8 dough-9 dough-10 dough-11 dough-12 dough-13 dough-14 dough-15 dough-16 dough-17 dough-18 dough-19 dough-20 dough-21 dough-22 dough-23 dough-24 dough-25 dough-26 dough-27 dough-28 dough-29 dough-30 dough-31 dough-32 dough-33 dough-34 dough-35 dough-36 dough-37 dough-38 dough-39 dough-40 dough-41 dough-42 dough-43
		toppings-1 toppings-2 toppings-3 toppings-4 toppings-5 toppings-6 toppings-7 toppings-8 toppings-9 toppings-10 toppings-11 toppings-12 toppings-13 toppings-14 toppings-15 toppings-16 toppings-17 toppings-18 toppings-19 toppings-20 toppings-21 toppings-22 toppings-23 toppings-24 toppings-25 toppings-26 toppings-27 toppings-28 toppings-29 toppings-30 toppings-31 toppings-32 toppings-33 toppings-34 toppings-35 toppings-36 toppings-37 toppings-38 toppings-39 toppings-40 toppings-41 toppings-42 toppings-43
		cheese-1 cheese-2 cheese-3 cheese-4 cheese-5 cheese-6 cheese-7 cheese-8 cheese-9 cheese-10 cheese-11 cheese-12 cheese-13 cheese-14 cheese-15 cheese-16 cheese-17 cheese-18 cheese-19 cheese-20 cheese-21 cheese-22 cheese-23 cheese-24 cheese-25 cheese-26 cheese-27 cheese-28 cheese-29 cheese-30 cheese-31 cheese-32 cheese-33 cheese-34 cheese-35 cheese-36 cheese-37 cheese-38 cheese-39 cheese-40 cheese-41 cheese-42 cheese-43
		potato-1 potato-2 potato-3 potato-4 potato-5 potato-6 potato-7
		fries-1 fries-2 fries-3 fries-4 fries-5 fries-6 fries-7
		pizza-1 pizza-2 pizza-3 pizza-4 pizza-5 pizza-6 pizza-7 pizza-8 pizza-9 pizza-10 pizza-11 pizza-12 pizza-13 pizza-14 pizza-15 pizza-16 pizza-17 pizza-18 pizza-19 pizza-20 pizza-21 pizza-22 pizza-23 pizza-24 pizza-25 pizza-26 pizza-27 pizza-28 pizza-29 pizza-30 pizza-31 pizza-32 pizza-33 pizza-34 pizza-35 pizza-36 pizza-37 pizza-38 pizza-39 pizza-40 pizza-41 pizza-42 pizza-43
		kitchen table bar
	)
	(:init
		(LOCATION kitchen)
		(LOCATION table)
		(LOCATION bar)
		(CUSTOMER customer-1)
		(CUSTOMER customer-2)
		(CUSTOMER customer-3)
		(CUSTOMER customer-4)
		(CUSTOMER customer-5)
		(CUSTOMER customer-6)
		(CUSTOMER customer-7)
		(CUSTOMER customer-8)
		(CUSTOMER customer-9)
		(CUSTOMER customer-10)
		(CUSTOMER customer-11)
		(CUSTOMER customer-12)
		(CUSTOMER customer-13)
		(CUSTOMER customer-14)
		(CUSTOMER customer-15)
		(CUSTOMER customer-16)
		(CUSTOMER customer-17)
		(CUSTOMER customer-18)
		(CUSTOMER customer-19)
		(CUSTOMER customer-20)
		(CUSTOMER customer-21)
		(CUSTOMER customer-22)
		(CUSTOMER customer-23)
		(CUSTOMER customer-24)
		(CUSTOMER customer-25)
		(CUSTOMER customer-26)
		(CUSTOMER customer-27)
		(CUSTOMER customer-28)
		(CUSTOMER customer-29)
		(CUSTOMER customer-30)
		(CUSTOMER customer-31)
		(CUSTOMER customer-32)
		(CUSTOMER customer-33)
		(CUSTOMER customer-34)
		(CUSTOMER customer-35)
		(CUSTOMER customer-36)
		(CUSTOMER customer-37)
		(CUSTOMER customer-38)
		(CUSTOMER customer-39)
		(CUSTOMER customer-40)
		(CUSTOMER customer-41)
		(CUSTOMER customer-42)
		(CUSTOMER customer-43)
		(CUSTOMER customer-44)
		(CUSTOMER customer-45)
		(CUSTOMER customer-46)
		(CUSTOMER customer-47)
		(CUSTOMER customer-48)
		(CUSTOMER customer-49)
		(CUSTOMER customer-50)
		(SERVER server-1)
		(DOUGH dough-1)
		(DOUGH dough-2)
		(DOUGH dough-3)
		(DOUGH dough-4)
		(DOUGH dough-5)
		(DOUGH dough-6)
		(DOUGH dough-7)
		(DOUGH dough-8)
		(DOUGH dough-9)
		(DOUGH dough-10)
		(DOUGH dough-11)
		(DOUGH dough-12)
		(DOUGH dough-13)
		(DOUGH dough-14)
		(DOUGH dough-15)
		(DOUGH dough-16)
		(DOUGH dough-17)
		(DOUGH dough-18)
		(DOUGH dough-19)
		(DOUGH dough-20)
		(DOUGH dough-21)
		(DOUGH dough-22)
		(DOUGH dough-23)
		(DOUGH dough-24)
		(DOUGH dough-25)
		(DOUGH dough-26)
		(DOUGH dough-27)
		(DOUGH dough-28)
		(DOUGH dough-29)
		(DOUGH dough-30)
		(DOUGH dough-31)
		(DOUGH dough-32)
		(DOUGH dough-33)
		(DOUGH dough-34)
		(DOUGH dough-35)
		(DOUGH dough-36)
		(DOUGH dough-37)
		(DOUGH dough-38)
		(DOUGH dough-39)
		(DOUGH dough-40)
		(DOUGH dough-41)
		(DOUGH dough-42)
		(DOUGH dough-43)
		(TOPPINGS toppings-1)
		(TOPPINGS toppings-2)
		(TOPPINGS toppings-3)
		(TOPPINGS toppings-4)
		(TOPPINGS toppings-5)
		(TOPPINGS toppings-6)
		(TOPPINGS toppings-7)
		(TOPPINGS toppings-8)
		(TOPPINGS toppings-9)
		(TOPPINGS toppings-10)
		(TOPPINGS toppings-11)
		(TOPPINGS toppings-12)
		(TOPPINGS toppings-13)
		(TOPPINGS toppings-14)
		(TOPPINGS toppings-15)
		(TOPPINGS toppings-16)
		(TOPPINGS toppings-17)
		(TOPPINGS toppings-18)
		(TOPPINGS toppings-19)
		(TOPPINGS toppings-20)
		(TOPPINGS toppings-21)
		(TOPPINGS toppings-22)
		(TOPPINGS toppings-23)
		(TOPPINGS toppings-24)
		(TOPPINGS toppings-25)
		(TOPPINGS toppings-26)
		(TOPPINGS toppings-27)
		(TOPPINGS toppings-28)
		(TOPPINGS toppings-29)
		(TOPPINGS toppings-30)
		(TOPPINGS toppings-31)
		(TOPPINGS toppings-32)
		(TOPPINGS toppings-33)
		(TOPPINGS toppings-34)
		(TOPPINGS toppings-35)
		(TOPPINGS toppings-36)
		(TOPPINGS toppings-37)
		(TOPPINGS toppings-38)
		(TOPPINGS toppings-39)
		(TOPPINGS toppings-40)
		(TOPPINGS toppings-41)
		(TOPPINGS toppings-42)
		(TOPPINGS toppings-43)
		(CHEESE cheese-1)
		(CHEESE cheese-2)
		(CHEESE cheese-3)
		(CHEESE cheese-4)
		(CHEESE cheese-5)
		(CHEESE cheese-6)
		(CHEESE cheese-7)
		(CHEESE cheese-8)
		(CHEESE cheese-9)
		(CHEESE cheese-10)
		(CHEESE cheese-11)
		(CHEESE cheese-12)
		(CHEESE cheese-13)
		(CHEESE cheese-14)
		(CHEESE cheese-15)
		(CHEESE cheese-16)
		(CHEESE cheese-17)
		(CHEESE cheese-18)
		(CHEESE cheese-19)
		(CHEESE cheese-20)
		(CHEESE cheese-21)
		(CHEESE cheese-22)
		(CHEESE cheese-23)
		(CHEESE cheese-24)
		(CHEESE cheese-25)
		(CHEESE cheese-26)
		(CHEESE cheese-27)
		(CHEESE cheese-28)
		(CHEESE cheese-29)
		(CHEESE cheese-30)
		(CHEESE cheese-31)
		(CHEESE cheese-32)
		(CHEESE cheese-33)
		(CHEESE cheese-34)
		(CHEESE cheese-35)
		(CHEESE cheese-36)
		(CHEESE cheese-37)
		(CHEESE cheese-38)
		(CHEESE cheese-39)
		(CHEESE cheese-40)
		(CHEESE cheese-41)
		(CHEESE cheese-42)
		(CHEESE cheese-43)
		(POTATO potato-1)
		(POTATO potato-2)
		(POTATO potato-3)
		(POTATO potato-4)
		(POTATO potato-5)
		(POTATO potato-6)
		(POTATO potato-7)
		(PIZZA pizza-1)
		(PIZZA pizza-2)
		(PIZZA pizza-3)
		(PIZZA pizza-4)
		(PIZZA pizza-5)
		(PIZZA pizza-6)
		(PIZZA pizza-7)
		(PIZZA pizza-8)
		(PIZZA pizza-9)
		(PIZZA pizza-10)
		(PIZZA pizza-11)
		(PIZZA pizza-12)
		(PIZZA pizza-13)
		(PIZZA pizza-14)
		(PIZZA pizza-15)
		(PIZZA pizza-16)
		(PIZZA pizza-17)
		(PIZZA pizza-18)
		(PIZZA pizza-19)
		(PIZZA pizza-20)
		(PIZZA pizza-21)
		(PIZZA pizza-22)
		(PIZZA pizza-23)
		(PIZZA pizza-24)
		(PIZZA pizza-25)
		(PIZZA pizza-26)
		(PIZZA pizza-27)
		(PIZZA pizza-28)
		(PIZZA pizza-29)
		(PIZZA pizza-30)
		(PIZZA pizza-31)
		(PIZZA pizza-32)
		(PIZZA pizza-33)
		(PIZZA pizza-34)
		(PIZZA pizza-35)
		(PIZZA pizza-36)
		(PIZZA pizza-37)
		(PIZZA pizza-38)
		(PIZZA pizza-39)
		(PIZZA pizza-40)
		(PIZZA pizza-41)
		(PIZZA pizza-42)
		(PIZZA pizza-43)
		(FRIES fries-1)
		(FRIES fries-2)
		(FRIES fries-3)
		(FRIES fries-4)
		(FRIES fries-5)
		(FRIES fries-6)
		(FRIES fries-7)
		(waiting-at customer-1 bar)
		(ordered-pizza customer-1)
		(waiting-at customer-2 table)
		(ordered-pizza customer-2)
		(waiting-at customer-3 table)
		(ordered-pizza customer-3)
		(waiting-at customer-4 table)
		(ordered-pizza customer-4)
		(waiting-at customer-5 bar)
		(ordered-pizza customer-5)
		(waiting-at customer-6 table)
		(ordered-pizza customer-6)
		(waiting-at customer-7 table)
		(ordered-pizza customer-7)
		(waiting-at customer-8 table)
		(ordered-pizza customer-8)
		(waiting-at customer-9 bar)
		(ordered-pizza customer-9)
		(waiting-at customer-10 table)
		(ordered-pizza customer-10)
		(waiting-at customer-11 bar)
		(ordered-pizza customer-11)
		(waiting-at customer-12 table)
		(ordered-pizza customer-12)
		(waiting-at customer-13 bar)
		(ordered-pizza customer-13)
		(waiting-at customer-14 bar)
		(ordered-pizza customer-14)
		(waiting-at customer-15 table)
		(ordered-pizza customer-15)
		(waiting-at customer-16 table)
		(ordered-pizza customer-16)
		(waiting-at customer-17 table)
		(ordered-pizza customer-17)
		(waiting-at customer-18 table)
		(ordered-pizza customer-18)
		(waiting-at customer-19 bar)
		(ordered-pizza customer-19)
		(waiting-at customer-20 bar)
		(ordered-pizza customer-20)
		(waiting-at customer-21 bar)
		(ordered-pizza customer-21)
		(waiting-at customer-22 bar)
		(ordered-pizza customer-22)
		(waiting-at customer-23 bar)
		(ordered-pizza customer-23)
		(waiting-at customer-24 bar)
		(ordered-pizza customer-24)
		(waiting-at customer-25 table)
		(ordered-pizza customer-25)
		(waiting-at customer-26 bar)
		(ordered-pizza customer-26)
		(waiting-at customer-27 table)
		(ordered-pizza customer-27)
		(waiting-at customer-28 table)
		(ordered-pizza customer-28)
		(waiting-at customer-29 table)
		(ordered-pizza customer-29)
		(waiting-at customer-30 table)
		(ordered-pizza customer-30)
		(waiting-at customer-31 table)
		(ordered-pizza customer-31)
		(waiting-at customer-32 bar)
		(ordered-pizza customer-32)
		(waiting-at customer-33 table)
		(ordered-pizza customer-33)
		(waiting-at customer-34 table)
		(ordered-pizza customer-34)
		(waiting-at customer-35 table)
		(ordered-pizza customer-35)
		(waiting-at customer-36 bar)
		(ordered-pizza customer-36)
		(waiting-at customer-37 table)
		(ordered-pizza customer-37)
		(waiting-at customer-38 bar)
		(ordered-pizza customer-38)
		(waiting-at customer-39 bar)
		(ordered-pizza customer-39)
		(waiting-at customer-40 bar)
		(ordered-pizza customer-40)
		(waiting-at customer-41 table)
		(ordered-pizza customer-41)
		(waiting-at customer-42 bar)
		(ordered-pizza customer-42)
		(waiting-at customer-43 table)
		(ordered-pizza customer-43)
		(waiting-at customer-44 bar)
		(ordered-fries customer-44)
		(waiting-at customer-45 bar)
		(ordered-fries customer-45)
		(waiting-at customer-46 table)
		(ordered-fries customer-46)
		(waiting-at customer-47 table)
		(ordered-fries customer-47)
		(waiting-at customer-48 bar)
		(ordered-fries customer-48)
		(waiting-at customer-49 table)
		(ordered-fries customer-49)
		(waiting-at customer-50 table)
		(ordered-fries customer-50)
		(at server-1 kitchen)
		(empty-hand server-1)
		(at dough-1 kitchen)
		(at dough-2 kitchen)
		(at dough-3 kitchen)
		(at dough-4 kitchen)
		(at dough-5 kitchen)
		(at dough-6 kitchen)
		(at dough-7 kitchen)
		(at dough-8 kitchen)
		(at dough-9 kitchen)
		(at dough-10 kitchen)
		(at dough-11 kitchen)
		(at dough-12 kitchen)
		(at dough-13 kitchen)
		(at dough-14 kitchen)
		(at dough-15 kitchen)
		(at dough-16 kitchen)
		(at dough-17 kitchen)
		(at dough-18 kitchen)
		(at dough-19 kitchen)
		(at dough-20 kitchen)
		(at dough-21 kitchen)
		(at dough-22 kitchen)
		(at dough-23 kitchen)
		(at dough-24 kitchen)
		(at dough-25 kitchen)
		(at dough-26 kitchen)
		(at dough-27 kitchen)
		(at dough-28 kitchen)
		(at dough-29 kitchen)
		(at dough-30 kitchen)
		(at dough-31 kitchen)
		(at dough-32 kitchen)
		(at dough-33 kitchen)
		(at dough-34 kitchen)
		(at dough-35 kitchen)
		(at dough-36 kitchen)
		(at dough-37 kitchen)
		(at dough-38 kitchen)
		(at dough-39 kitchen)
		(at dough-40 kitchen)
		(at dough-41 kitchen)
		(at dough-42 kitchen)
		(at dough-43 kitchen)
		(at toppings-1 kitchen)
		(at toppings-2 kitchen)
		(at toppings-3 kitchen)
		(at toppings-4 kitchen)
		(at toppings-5 kitchen)
		(at toppings-6 kitchen)
		(at toppings-7 kitchen)
		(at toppings-8 kitchen)
		(at toppings-9 kitchen)
		(at toppings-10 kitchen)
		(at toppings-11 kitchen)
		(at toppings-12 kitchen)
		(at toppings-13 kitchen)
		(at toppings-14 kitchen)
		(at toppings-15 kitchen)
		(at toppings-16 kitchen)
		(at toppings-17 kitchen)
		(at toppings-18 kitchen)
		(at toppings-19 kitchen)
		(at toppings-20 kitchen)
		(at toppings-21 kitchen)
		(at toppings-22 kitchen)
		(at toppings-23 kitchen)
		(at toppings-24 kitchen)
		(at toppings-25 kitchen)
		(at toppings-26 kitchen)
		(at toppings-27 kitchen)
		(at toppings-28 kitchen)
		(at toppings-29 kitchen)
		(at toppings-30 kitchen)
		(at toppings-31 kitchen)
		(at toppings-32 kitchen)
		(at toppings-33 kitchen)
		(at toppings-34 kitchen)
		(at toppings-35 kitchen)
		(at toppings-36 kitchen)
		(at toppings-37 kitchen)
		(at toppings-38 kitchen)
		(at toppings-39 kitchen)
		(at toppings-40 kitchen)
		(at toppings-41 kitchen)
		(at toppings-42 kitchen)
		(at toppings-43 kitchen)
		(at cheese-1 kitchen)
		(at cheese-2 kitchen)
		(at cheese-3 kitchen)
		(at cheese-4 kitchen)
		(at cheese-5 kitchen)
		(at cheese-6 kitchen)
		(at cheese-7 kitchen)
		(at cheese-8 kitchen)
		(at cheese-9 kitchen)
		(at cheese-10 kitchen)
		(at cheese-11 kitchen)
		(at cheese-12 kitchen)
		(at cheese-13 kitchen)
		(at cheese-14 kitchen)
		(at cheese-15 kitchen)
		(at cheese-16 kitchen)
		(at cheese-17 kitchen)
		(at cheese-18 kitchen)
		(at cheese-19 kitchen)
		(at cheese-20 kitchen)
		(at cheese-21 kitchen)
		(at cheese-22 kitchen)
		(at cheese-23 kitchen)
		(at cheese-24 kitchen)
		(at cheese-25 kitchen)
		(at cheese-26 kitchen)
		(at cheese-27 kitchen)
		(at cheese-28 kitchen)
		(at cheese-29 kitchen)
		(at cheese-30 kitchen)
		(at cheese-31 kitchen)
		(at cheese-32 kitchen)
		(at cheese-33 kitchen)
		(at cheese-34 kitchen)
		(at cheese-35 kitchen)
		(at cheese-36 kitchen)
		(at cheese-37 kitchen)
		(at cheese-38 kitchen)
		(at cheese-39 kitchen)
		(at cheese-40 kitchen)
		(at cheese-41 kitchen)
		(at cheese-42 kitchen)
		(at cheese-43 kitchen)
		(at potato-1 kitchen)
		(at potato-2 kitchen)
		(at potato-3 kitchen)
		(at potato-4 kitchen)
		(at potato-5 kitchen)
		(at potato-6 kitchen)
		(at potato-7 kitchen)
		(full-potato potato-1)
		(full-potato potato-2)
		(full-potato potato-3)
		(full-potato potato-4)
		(full-potato potato-5)
		(full-potato potato-6)
		(full-potato potato-7)
		(no-exist-pizza pizza-1)
		(no-exist-pizza pizza-2)
		(no-exist-pizza pizza-3)
		(no-exist-pizza pizza-4)
		(no-exist-pizza pizza-5)
		(no-exist-pizza pizza-6)
		(no-exist-pizza pizza-7)
		(no-exist-pizza pizza-8)
		(no-exist-pizza pizza-9)
		(no-exist-pizza pizza-10)
		(no-exist-pizza pizza-11)
		(no-exist-pizza pizza-12)
		(no-exist-pizza pizza-13)
		(no-exist-pizza pizza-14)
		(no-exist-pizza pizza-15)
		(no-exist-pizza pizza-16)
		(no-exist-pizza pizza-17)
		(no-exist-pizza pizza-18)
		(no-exist-pizza pizza-19)
		(no-exist-pizza pizza-20)
		(no-exist-pizza pizza-21)
		(no-exist-pizza pizza-22)
		(no-exist-pizza pizza-23)
		(no-exist-pizza pizza-24)
		(no-exist-pizza pizza-25)
		(no-exist-pizza pizza-26)
		(no-exist-pizza pizza-27)
		(no-exist-pizza pizza-28)
		(no-exist-pizza pizza-29)
		(no-exist-pizza pizza-30)
		(no-exist-pizza pizza-31)
		(no-exist-pizza pizza-32)
		(no-exist-pizza pizza-33)
		(no-exist-pizza pizza-34)
		(no-exist-pizza pizza-35)
		(no-exist-pizza pizza-36)
		(no-exist-pizza pizza-37)
		(no-exist-pizza pizza-38)
		(no-exist-pizza pizza-39)
		(no-exist-pizza pizza-40)
		(no-exist-pizza pizza-41)
		(no-exist-pizza pizza-42)
		(no-exist-pizza pizza-43)
		(no-exist-fries fries-1)
		(no-exist-fries fries-2)
		(no-exist-fries fries-3)
		(no-exist-fries fries-4)
		(no-exist-fries fries-5)
		(no-exist-fries fries-6)
		(no-exist-fries fries-7)
	)
	(:goal (and
		(served customer-1)
		(served customer-2)
		(served customer-3)
		(served customer-4)
		(served customer-5)
		(served customer-6)
		(served customer-7)
		(served customer-8)
		(served customer-9)
		(served customer-10)
		(served customer-11)
		(served customer-12)
		(served customer-13)
		(served customer-14)
		(served customer-15)
		(served customer-16)
		(served customer-17)
		(served customer-18)
		(served customer-19)
		(served customer-20)
		(served customer-21)
		(served customer-22)
		(served customer-23)
		(served customer-24)
		(served customer-25)
		(served customer-26)
		(served customer-27)
		(served customer-28)
		(served customer-29)
		(served customer-30)
		(served customer-31)
		(served customer-32)
		(served customer-33)
		(served customer-34)
		(served customer-35)
		(served customer-36)
		(served customer-37)
		(served customer-38)
		(served customer-39)
		(served customer-40)
		(served customer-41)
		(served customer-42)
		(served customer-43)
		(served customer-44)
		(served customer-45)
		(served customer-46)
		(served customer-47)
		(served customer-48)
		(served customer-49)
		(served customer-50)
		)
	)
)
