(define (problem restaurant-strips-s1-c20)
	(:domain restaurant-strips)
	(:objects
		customer-1 customer-2 customer-3 customer-4 customer-5 customer-6 customer-7 customer-8 customer-9 customer-10 customer-11 customer-12 customer-13 customer-14 customer-15 customer-16 customer-17 customer-18 customer-19 customer-20
		server-1
		dough-1 dough-2 dough-3
		toppings-1 toppings-2 toppings-3
		cheese-1 cheese-2 cheese-3
		potato-1 potato-2 potato-3 potato-4 potato-5 potato-6 potato-7 potato-8 potato-9 potato-10 potato-11 potato-12 potato-13 potato-14 potato-15 potato-16 potato-17
		fries-1 fries-2 fries-3 fries-4 fries-5 fries-6 fries-7 fries-8 fries-9 fries-10 fries-11 fries-12 fries-13 fries-14 fries-15 fries-16 fries-17
		pizza-1 pizza-2 pizza-3
		kitchen table bar
	)
	(:init
		(LOCATION kitchen)
		(LOCATION table)
		(LOCATION bar)
		(CUSTOMER customer-1)
		(CUSTOMER customer-2)
		(CUSTOMER customer-3)
		(CUSTOMER customer-4)
		(CUSTOMER customer-5)
		(CUSTOMER customer-6)
		(CUSTOMER customer-7)
		(CUSTOMER customer-8)
		(CUSTOMER customer-9)
		(CUSTOMER customer-10)
		(CUSTOMER customer-11)
		(CUSTOMER customer-12)
		(CUSTOMER customer-13)
		(CUSTOMER customer-14)
		(CUSTOMER customer-15)
		(CUSTOMER customer-16)
		(CUSTOMER customer-17)
		(CUSTOMER customer-18)
		(CUSTOMER customer-19)
		(CUSTOMER customer-20)
		(SERVER server-1)
		(DOUGH dough-1)
		(DOUGH dough-2)
		(DOUGH dough-3)
		(TOPPINGS toppings-1)
		(TOPPINGS toppings-2)
		(TOPPINGS toppings-3)
		(CHEESE cheese-1)
		(CHEESE cheese-2)
		(CHEESE cheese-3)
		(POTATO potato-1)
		(POTATO potato-2)
		(POTATO potato-3)
		(POTATO potato-4)
		(POTATO potato-5)
		(POTATO potato-6)
		(POTATO potato-7)
		(POTATO potato-8)
		(POTATO potato-9)
		(POTATO potato-10)
		(POTATO potato-11)
		(POTATO potato-12)
		(POTATO potato-13)
		(POTATO potato-14)
		(POTATO potato-15)
		(POTATO potato-16)
		(POTATO potato-17)
		(PIZZA pizza-1)
		(PIZZA pizza-2)
		(PIZZA pizza-3)
		(FRIES fries-1)
		(FRIES fries-2)
		(FRIES fries-3)
		(FRIES fries-4)
		(FRIES fries-5)
		(FRIES fries-6)
		(FRIES fries-7)
		(FRIES fries-8)
		(FRIES fries-9)
		(FRIES fries-10)
		(FRIES fries-11)
		(FRIES fries-12)
		(FRIES fries-13)
		(FRIES fries-14)
		(FRIES fries-15)
		(FRIES fries-16)
		(FRIES fries-17)
		(waiting-at customer-1 bar)
		(ordered-pizza customer-1)
		(waiting-at customer-2 table)
		(ordered-pizza customer-2)
		(waiting-at customer-3 bar)
		(ordered-pizza customer-3)
		(waiting-at customer-4 table)
		(ordered-fries customer-4)
		(waiting-at customer-5 bar)
		(ordered-fries customer-5)
		(waiting-at customer-6 table)
		(ordered-fries customer-6)
		(waiting-at customer-7 bar)
		(ordered-fries customer-7)
		(waiting-at customer-8 table)
		(ordered-fries customer-8)
		(waiting-at customer-9 bar)
		(ordered-fries customer-9)
		(waiting-at customer-10 bar)
		(ordered-fries customer-10)
		(waiting-at customer-11 bar)
		(ordered-fries customer-11)
		(waiting-at customer-12 table)
		(ordered-fries customer-12)
		(waiting-at customer-13 table)
		(ordered-fries customer-13)
		(waiting-at customer-14 bar)
		(ordered-fries customer-14)
		(waiting-at customer-15 table)
		(ordered-fries customer-15)
		(waiting-at customer-16 table)
		(ordered-fries customer-16)
		(waiting-at customer-17 bar)
		(ordered-fries customer-17)
		(waiting-at customer-18 table)
		(ordered-fries customer-18)
		(waiting-at customer-19 bar)
		(ordered-fries customer-19)
		(waiting-at customer-20 table)
		(ordered-fries customer-20)
		(at server-1 kitchen)
		(empty-hand server-1)
		(at dough-1 kitchen)
		(at dough-2 kitchen)
		(at dough-3 kitchen)
		(at toppings-1 kitchen)
		(at toppings-2 kitchen)
		(at toppings-3 kitchen)
		(at cheese-1 kitchen)
		(at cheese-2 kitchen)
		(at cheese-3 kitchen)
		(at potato-1 kitchen)
		(at potato-2 kitchen)
		(at potato-3 kitchen)
		(at potato-4 kitchen)
		(at potato-5 kitchen)
		(at potato-6 kitchen)
		(at potato-7 kitchen)
		(at potato-8 kitchen)
		(at potato-9 kitchen)
		(at potato-10 kitchen)
		(at potato-11 kitchen)
		(at potato-12 kitchen)
		(at potato-13 kitchen)
		(at potato-14 kitchen)
		(at potato-15 kitchen)
		(at potato-16 kitchen)
		(at potato-17 kitchen)
		(full-potato potato-1)
		(full-potato potato-2)
		(full-potato potato-3)
		(full-potato potato-4)
		(full-potato potato-5)
		(full-potato potato-6)
		(full-potato potato-7)
		(full-potato potato-8)
		(full-potato potato-9)
		(full-potato potato-10)
		(full-potato potato-11)
		(full-potato potato-12)
		(full-potato potato-13)
		(full-potato potato-14)
		(full-potato potato-15)
		(full-potato potato-16)
		(full-potato potato-17)
		(no-exist-pizza pizza-1)
		(no-exist-pizza pizza-2)
		(no-exist-pizza pizza-3)
		(no-exist-fries fries-1)
		(no-exist-fries fries-2)
		(no-exist-fries fries-3)
		(no-exist-fries fries-4)
		(no-exist-fries fries-5)
		(no-exist-fries fries-6)
		(no-exist-fries fries-7)
		(no-exist-fries fries-8)
		(no-exist-fries fries-9)
		(no-exist-fries fries-10)
		(no-exist-fries fries-11)
		(no-exist-fries fries-12)
		(no-exist-fries fries-13)
		(no-exist-fries fries-14)
		(no-exist-fries fries-15)
		(no-exist-fries fries-16)
		(no-exist-fries fries-17)
	)
	(:goal (and
		(served customer-1)
		(served customer-2)
		(served customer-3)
		(served customer-4)
		(served customer-5)
		(served customer-6)
		(served customer-7)
		(served customer-8)
		(served customer-9)
		(served customer-10)
		(served customer-11)
		(served customer-12)
		(served customer-13)
		(served customer-14)
		(served customer-15)
		(served customer-16)
		(served customer-17)
		(served customer-18)
		(served customer-19)
		(served customer-20)
		)
	)
)
