(define (problem restaurant-strips-s1-c100)
	(:domain restaurant-strips)
	(:objects
		customer-1 customer-2 customer-3 customer-4 customer-5 customer-6 customer-7 customer-8 customer-9 customer-10 customer-11 customer-12 customer-13 customer-14 customer-15 customer-16 customer-17 customer-18 customer-19 customer-20 customer-21 customer-22 customer-23 customer-24 customer-25 customer-26 customer-27 customer-28 customer-29 customer-30 customer-31 customer-32 customer-33 customer-34 customer-35 customer-36 customer-37 customer-38 customer-39 customer-40 customer-41 customer-42 customer-43 customer-44 customer-45 customer-46 customer-47 customer-48 customer-49 customer-50 customer-51 customer-52 customer-53 customer-54 customer-55 customer-56 customer-57 customer-58 customer-59 customer-60 customer-61 customer-62 customer-63 customer-64 customer-65 customer-66 customer-67 customer-68 customer-69 customer-70 customer-71 customer-72 customer-73 customer-74 customer-75 customer-76 customer-77 customer-78 customer-79 customer-80 customer-81 customer-82 customer-83 customer-84 customer-85 customer-86 customer-87 customer-88 customer-89 customer-90 customer-91 customer-92 customer-93 customer-94 customer-95 customer-96 customer-97 customer-98 customer-99 customer-100
		server-1
		dough-1 dough-2 dough-3 dough-4 dough-5 dough-6 dough-7 dough-8 dough-9 dough-10 dough-11 dough-12 dough-13 dough-14 dough-15 dough-16 dough-17 dough-18 dough-19 dough-20 dough-21 dough-22 dough-23 dough-24 dough-25 dough-26 dough-27 dough-28 dough-29 dough-30 dough-31 dough-32 dough-33 dough-34 dough-35 dough-36 dough-37 dough-38 dough-39 dough-40 dough-41 dough-42 dough-43 dough-44 dough-45 dough-46 dough-47 dough-48 dough-49 dough-50 dough-51 dough-52 dough-53 dough-54 dough-55 dough-56 dough-57 dough-58 dough-59
		toppings-1 toppings-2 toppings-3 toppings-4 toppings-5 toppings-6 toppings-7 toppings-8 toppings-9 toppings-10 toppings-11 toppings-12 toppings-13 toppings-14 toppings-15 toppings-16 toppings-17 toppings-18 toppings-19 toppings-20 toppings-21 toppings-22 toppings-23 toppings-24 toppings-25 toppings-26 toppings-27 toppings-28 toppings-29 toppings-30 toppings-31 toppings-32 toppings-33 toppings-34 toppings-35 toppings-36 toppings-37 toppings-38 toppings-39 toppings-40 toppings-41 toppings-42 toppings-43 toppings-44 toppings-45 toppings-46 toppings-47 toppings-48 toppings-49 toppings-50 toppings-51 toppings-52 toppings-53 toppings-54 toppings-55 toppings-56 toppings-57 toppings-58 toppings-59
		cheese-1 cheese-2 cheese-3 cheese-4 cheese-5 cheese-6 cheese-7 cheese-8 cheese-9 cheese-10 cheese-11 cheese-12 cheese-13 cheese-14 cheese-15 cheese-16 cheese-17 cheese-18 cheese-19 cheese-20 cheese-21 cheese-22 cheese-23 cheese-24 cheese-25 cheese-26 cheese-27 cheese-28 cheese-29 cheese-30 cheese-31 cheese-32 cheese-33 cheese-34 cheese-35 cheese-36 cheese-37 cheese-38 cheese-39 cheese-40 cheese-41 cheese-42 cheese-43 cheese-44 cheese-45 cheese-46 cheese-47 cheese-48 cheese-49 cheese-50 cheese-51 cheese-52 cheese-53 cheese-54 cheese-55 cheese-56 cheese-57 cheese-58 cheese-59
		potato-1 potato-2 potato-3 potato-4 potato-5 potato-6 potato-7 potato-8 potato-9 potato-10 potato-11 potato-12 potato-13 potato-14 potato-15 potato-16 potato-17 potato-18 potato-19 potato-20 potato-21 potato-22 potato-23 potato-24 potato-25 potato-26 potato-27 potato-28 potato-29 potato-30 potato-31 potato-32 potato-33 potato-34 potato-35 potato-36 potato-37 potato-38 potato-39 potato-40 potato-41
		fries-1 fries-2 fries-3 fries-4 fries-5 fries-6 fries-7 fries-8 fries-9 fries-10 fries-11 fries-12 fries-13 fries-14 fries-15 fries-16 fries-17 fries-18 fries-19 fries-20 fries-21 fries-22 fries-23 fries-24 fries-25 fries-26 fries-27 fries-28 fries-29 fries-30 fries-31 fries-32 fries-33 fries-34 fries-35 fries-36 fries-37 fries-38 fries-39 fries-40 fries-41
		pizza-1 pizza-2 pizza-3 pizza-4 pizza-5 pizza-6 pizza-7 pizza-8 pizza-9 pizza-10 pizza-11 pizza-12 pizza-13 pizza-14 pizza-15 pizza-16 pizza-17 pizza-18 pizza-19 pizza-20 pizza-21 pizza-22 pizza-23 pizza-24 pizza-25 pizza-26 pizza-27 pizza-28 pizza-29 pizza-30 pizza-31 pizza-32 pizza-33 pizza-34 pizza-35 pizza-36 pizza-37 pizza-38 pizza-39 pizza-40 pizza-41 pizza-42 pizza-43 pizza-44 pizza-45 pizza-46 pizza-47 pizza-48 pizza-49 pizza-50 pizza-51 pizza-52 pizza-53 pizza-54 pizza-55 pizza-56 pizza-57 pizza-58 pizza-59
		kitchen table bar
	)
	(:init
		(LOCATION kitchen)
		(LOCATION table)
		(LOCATION bar)
		(CUSTOMER customer-1)
		(CUSTOMER customer-2)
		(CUSTOMER customer-3)
		(CUSTOMER customer-4)
		(CUSTOMER customer-5)
		(CUSTOMER customer-6)
		(CUSTOMER customer-7)
		(CUSTOMER customer-8)
		(CUSTOMER customer-9)
		(CUSTOMER customer-10)
		(CUSTOMER customer-11)
		(CUSTOMER customer-12)
		(CUSTOMER customer-13)
		(CUSTOMER customer-14)
		(CUSTOMER customer-15)
		(CUSTOMER customer-16)
		(CUSTOMER customer-17)
		(CUSTOMER customer-18)
		(CUSTOMER customer-19)
		(CUSTOMER customer-20)
		(CUSTOMER customer-21)
		(CUSTOMER customer-22)
		(CUSTOMER customer-23)
		(CUSTOMER customer-24)
		(CUSTOMER customer-25)
		(CUSTOMER customer-26)
		(CUSTOMER customer-27)
		(CUSTOMER customer-28)
		(CUSTOMER customer-29)
		(CUSTOMER customer-30)
		(CUSTOMER customer-31)
		(CUSTOMER customer-32)
		(CUSTOMER customer-33)
		(CUSTOMER customer-34)
		(CUSTOMER customer-35)
		(CUSTOMER customer-36)
		(CUSTOMER customer-37)
		(CUSTOMER customer-38)
		(CUSTOMER customer-39)
		(CUSTOMER customer-40)
		(CUSTOMER customer-41)
		(CUSTOMER customer-42)
		(CUSTOMER customer-43)
		(CUSTOMER customer-44)
		(CUSTOMER customer-45)
		(CUSTOMER customer-46)
		(CUSTOMER customer-47)
		(CUSTOMER customer-48)
		(CUSTOMER customer-49)
		(CUSTOMER customer-50)
		(CUSTOMER customer-51)
		(CUSTOMER customer-52)
		(CUSTOMER customer-53)
		(CUSTOMER customer-54)
		(CUSTOMER customer-55)
		(CUSTOMER customer-56)
		(CUSTOMER customer-57)
		(CUSTOMER customer-58)
		(CUSTOMER customer-59)
		(CUSTOMER customer-60)
		(CUSTOMER customer-61)
		(CUSTOMER customer-62)
		(CUSTOMER customer-63)
		(CUSTOMER customer-64)
		(CUSTOMER customer-65)
		(CUSTOMER customer-66)
		(CUSTOMER customer-67)
		(CUSTOMER customer-68)
		(CUSTOMER customer-69)
		(CUSTOMER customer-70)
		(CUSTOMER customer-71)
		(CUSTOMER customer-72)
		(CUSTOMER customer-73)
		(CUSTOMER customer-74)
		(CUSTOMER customer-75)
		(CUSTOMER customer-76)
		(CUSTOMER customer-77)
		(CUSTOMER customer-78)
		(CUSTOMER customer-79)
		(CUSTOMER customer-80)
		(CUSTOMER customer-81)
		(CUSTOMER customer-82)
		(CUSTOMER customer-83)
		(CUSTOMER customer-84)
		(CUSTOMER customer-85)
		(CUSTOMER customer-86)
		(CUSTOMER customer-87)
		(CUSTOMER customer-88)
		(CUSTOMER customer-89)
		(CUSTOMER customer-90)
		(CUSTOMER customer-91)
		(CUSTOMER customer-92)
		(CUSTOMER customer-93)
		(CUSTOMER customer-94)
		(CUSTOMER customer-95)
		(CUSTOMER customer-96)
		(CUSTOMER customer-97)
		(CUSTOMER customer-98)
		(CUSTOMER customer-99)
		(CUSTOMER customer-100)
		(SERVER server-1)
		(DOUGH dough-1)
		(DOUGH dough-2)
		(DOUGH dough-3)
		(DOUGH dough-4)
		(DOUGH dough-5)
		(DOUGH dough-6)
		(DOUGH dough-7)
		(DOUGH dough-8)
		(DOUGH dough-9)
		(DOUGH dough-10)
		(DOUGH dough-11)
		(DOUGH dough-12)
		(DOUGH dough-13)
		(DOUGH dough-14)
		(DOUGH dough-15)
		(DOUGH dough-16)
		(DOUGH dough-17)
		(DOUGH dough-18)
		(DOUGH dough-19)
		(DOUGH dough-20)
		(DOUGH dough-21)
		(DOUGH dough-22)
		(DOUGH dough-23)
		(DOUGH dough-24)
		(DOUGH dough-25)
		(DOUGH dough-26)
		(DOUGH dough-27)
		(DOUGH dough-28)
		(DOUGH dough-29)
		(DOUGH dough-30)
		(DOUGH dough-31)
		(DOUGH dough-32)
		(DOUGH dough-33)
		(DOUGH dough-34)
		(DOUGH dough-35)
		(DOUGH dough-36)
		(DOUGH dough-37)
		(DOUGH dough-38)
		(DOUGH dough-39)
		(DOUGH dough-40)
		(DOUGH dough-41)
		(DOUGH dough-42)
		(DOUGH dough-43)
		(DOUGH dough-44)
		(DOUGH dough-45)
		(DOUGH dough-46)
		(DOUGH dough-47)
		(DOUGH dough-48)
		(DOUGH dough-49)
		(DOUGH dough-50)
		(DOUGH dough-51)
		(DOUGH dough-52)
		(DOUGH dough-53)
		(DOUGH dough-54)
		(DOUGH dough-55)
		(DOUGH dough-56)
		(DOUGH dough-57)
		(DOUGH dough-58)
		(DOUGH dough-59)
		(TOPPINGS toppings-1)
		(TOPPINGS toppings-2)
		(TOPPINGS toppings-3)
		(TOPPINGS toppings-4)
		(TOPPINGS toppings-5)
		(TOPPINGS toppings-6)
		(TOPPINGS toppings-7)
		(TOPPINGS toppings-8)
		(TOPPINGS toppings-9)
		(TOPPINGS toppings-10)
		(TOPPINGS toppings-11)
		(TOPPINGS toppings-12)
		(TOPPINGS toppings-13)
		(TOPPINGS toppings-14)
		(TOPPINGS toppings-15)
		(TOPPINGS toppings-16)
		(TOPPINGS toppings-17)
		(TOPPINGS toppings-18)
		(TOPPINGS toppings-19)
		(TOPPINGS toppings-20)
		(TOPPINGS toppings-21)
		(TOPPINGS toppings-22)
		(TOPPINGS toppings-23)
		(TOPPINGS toppings-24)
		(TOPPINGS toppings-25)
		(TOPPINGS toppings-26)
		(TOPPINGS toppings-27)
		(TOPPINGS toppings-28)
		(TOPPINGS toppings-29)
		(TOPPINGS toppings-30)
		(TOPPINGS toppings-31)
		(TOPPINGS toppings-32)
		(TOPPINGS toppings-33)
		(TOPPINGS toppings-34)
		(TOPPINGS toppings-35)
		(TOPPINGS toppings-36)
		(TOPPINGS toppings-37)
		(TOPPINGS toppings-38)
		(TOPPINGS toppings-39)
		(TOPPINGS toppings-40)
		(TOPPINGS toppings-41)
		(TOPPINGS toppings-42)
		(TOPPINGS toppings-43)
		(TOPPINGS toppings-44)
		(TOPPINGS toppings-45)
		(TOPPINGS toppings-46)
		(TOPPINGS toppings-47)
		(TOPPINGS toppings-48)
		(TOPPINGS toppings-49)
		(TOPPINGS toppings-50)
		(TOPPINGS toppings-51)
		(TOPPINGS toppings-52)
		(TOPPINGS toppings-53)
		(TOPPINGS toppings-54)
		(TOPPINGS toppings-55)
		(TOPPINGS toppings-56)
		(TOPPINGS toppings-57)
		(TOPPINGS toppings-58)
		(TOPPINGS toppings-59)
		(CHEESE cheese-1)
		(CHEESE cheese-2)
		(CHEESE cheese-3)
		(CHEESE cheese-4)
		(CHEESE cheese-5)
		(CHEESE cheese-6)
		(CHEESE cheese-7)
		(CHEESE cheese-8)
		(CHEESE cheese-9)
		(CHEESE cheese-10)
		(CHEESE cheese-11)
		(CHEESE cheese-12)
		(CHEESE cheese-13)
		(CHEESE cheese-14)
		(CHEESE cheese-15)
		(CHEESE cheese-16)
		(CHEESE cheese-17)
		(CHEESE cheese-18)
		(CHEESE cheese-19)
		(CHEESE cheese-20)
		(CHEESE cheese-21)
		(CHEESE cheese-22)
		(CHEESE cheese-23)
		(CHEESE cheese-24)
		(CHEESE cheese-25)
		(CHEESE cheese-26)
		(CHEESE cheese-27)
		(CHEESE cheese-28)
		(CHEESE cheese-29)
		(CHEESE cheese-30)
		(CHEESE cheese-31)
		(CHEESE cheese-32)
		(CHEESE cheese-33)
		(CHEESE cheese-34)
		(CHEESE cheese-35)
		(CHEESE cheese-36)
		(CHEESE cheese-37)
		(CHEESE cheese-38)
		(CHEESE cheese-39)
		(CHEESE cheese-40)
		(CHEESE cheese-41)
		(CHEESE cheese-42)
		(CHEESE cheese-43)
		(CHEESE cheese-44)
		(CHEESE cheese-45)
		(CHEESE cheese-46)
		(CHEESE cheese-47)
		(CHEESE cheese-48)
		(CHEESE cheese-49)
		(CHEESE cheese-50)
		(CHEESE cheese-51)
		(CHEESE cheese-52)
		(CHEESE cheese-53)
		(CHEESE cheese-54)
		(CHEESE cheese-55)
		(CHEESE cheese-56)
		(CHEESE cheese-57)
		(CHEESE cheese-58)
		(CHEESE cheese-59)
		(POTATO potato-1)
		(POTATO potato-2)
		(POTATO potato-3)
		(POTATO potato-4)
		(POTATO potato-5)
		(POTATO potato-6)
		(POTATO potato-7)
		(POTATO potato-8)
		(POTATO potato-9)
		(POTATO potato-10)
		(POTATO potato-11)
		(POTATO potato-12)
		(POTATO potato-13)
		(POTATO potato-14)
		(POTATO potato-15)
		(POTATO potato-16)
		(POTATO potato-17)
		(POTATO potato-18)
		(POTATO potato-19)
		(POTATO potato-20)
		(POTATO potato-21)
		(POTATO potato-22)
		(POTATO potato-23)
		(POTATO potato-24)
		(POTATO potato-25)
		(POTATO potato-26)
		(POTATO potato-27)
		(POTATO potato-28)
		(POTATO potato-29)
		(POTATO potato-30)
		(POTATO potato-31)
		(POTATO potato-32)
		(POTATO potato-33)
		(POTATO potato-34)
		(POTATO potato-35)
		(POTATO potato-36)
		(POTATO potato-37)
		(POTATO potato-38)
		(POTATO potato-39)
		(POTATO potato-40)
		(POTATO potato-41)
		(PIZZA pizza-1)
		(PIZZA pizza-2)
		(PIZZA pizza-3)
		(PIZZA pizza-4)
		(PIZZA pizza-5)
		(PIZZA pizza-6)
		(PIZZA pizza-7)
		(PIZZA pizza-8)
		(PIZZA pizza-9)
		(PIZZA pizza-10)
		(PIZZA pizza-11)
		(PIZZA pizza-12)
		(PIZZA pizza-13)
		(PIZZA pizza-14)
		(PIZZA pizza-15)
		(PIZZA pizza-16)
		(PIZZA pizza-17)
		(PIZZA pizza-18)
		(PIZZA pizza-19)
		(PIZZA pizza-20)
		(PIZZA pizza-21)
		(PIZZA pizza-22)
		(PIZZA pizza-23)
		(PIZZA pizza-24)
		(PIZZA pizza-25)
		(PIZZA pizza-26)
		(PIZZA pizza-27)
		(PIZZA pizza-28)
		(PIZZA pizza-29)
		(PIZZA pizza-30)
		(PIZZA pizza-31)
		(PIZZA pizza-32)
		(PIZZA pizza-33)
		(PIZZA pizza-34)
		(PIZZA pizza-35)
		(PIZZA pizza-36)
		(PIZZA pizza-37)
		(PIZZA pizza-38)
		(PIZZA pizza-39)
		(PIZZA pizza-40)
		(PIZZA pizza-41)
		(PIZZA pizza-42)
		(PIZZA pizza-43)
		(PIZZA pizza-44)
		(PIZZA pizza-45)
		(PIZZA pizza-46)
		(PIZZA pizza-47)
		(PIZZA pizza-48)
		(PIZZA pizza-49)
		(PIZZA pizza-50)
		(PIZZA pizza-51)
		(PIZZA pizza-52)
		(PIZZA pizza-53)
		(PIZZA pizza-54)
		(PIZZA pizza-55)
		(PIZZA pizza-56)
		(PIZZA pizza-57)
		(PIZZA pizza-58)
		(PIZZA pizza-59)
		(FRIES fries-1)
		(FRIES fries-2)
		(FRIES fries-3)
		(FRIES fries-4)
		(FRIES fries-5)
		(FRIES fries-6)
		(FRIES fries-7)
		(FRIES fries-8)
		(FRIES fries-9)
		(FRIES fries-10)
		(FRIES fries-11)
		(FRIES fries-12)
		(FRIES fries-13)
		(FRIES fries-14)
		(FRIES fries-15)
		(FRIES fries-16)
		(FRIES fries-17)
		(FRIES fries-18)
		(FRIES fries-19)
		(FRIES fries-20)
		(FRIES fries-21)
		(FRIES fries-22)
		(FRIES fries-23)
		(FRIES fries-24)
		(FRIES fries-25)
		(FRIES fries-26)
		(FRIES fries-27)
		(FRIES fries-28)
		(FRIES fries-29)
		(FRIES fries-30)
		(FRIES fries-31)
		(FRIES fries-32)
		(FRIES fries-33)
		(FRIES fries-34)
		(FRIES fries-35)
		(FRIES fries-36)
		(FRIES fries-37)
		(FRIES fries-38)
		(FRIES fries-39)
		(FRIES fries-40)
		(FRIES fries-41)
		(waiting-at customer-1 bar)
		(ordered-pizza customer-1)
		(waiting-at customer-2 bar)
		(ordered-pizza customer-2)
		(waiting-at customer-3 table)
		(ordered-pizza customer-3)
		(waiting-at customer-4 table)
		(ordered-pizza customer-4)
		(waiting-at customer-5 table)
		(ordered-pizza customer-5)
		(waiting-at customer-6 bar)
		(ordered-pizza customer-6)
		(waiting-at customer-7 bar)
		(ordered-pizza customer-7)
		(waiting-at customer-8 table)
		(ordered-pizza customer-8)
		(waiting-at customer-9 table)
		(ordered-pizza customer-9)
		(waiting-at customer-10 table)
		(ordered-pizza customer-10)
		(waiting-at customer-11 bar)
		(ordered-pizza customer-11)
		(waiting-at customer-12 table)
		(ordered-pizza customer-12)
		(waiting-at customer-13 bar)
		(ordered-pizza customer-13)
		(waiting-at customer-14 table)
		(ordered-pizza customer-14)
		(waiting-at customer-15 table)
		(ordered-pizza customer-15)
		(waiting-at customer-16 bar)
		(ordered-pizza customer-16)
		(waiting-at customer-17 bar)
		(ordered-pizza customer-17)
		(waiting-at customer-18 table)
		(ordered-pizza customer-18)
		(waiting-at customer-19 bar)
		(ordered-pizza customer-19)
		(waiting-at customer-20 bar)
		(ordered-pizza customer-20)
		(waiting-at customer-21 table)
		(ordered-pizza customer-21)
		(waiting-at customer-22 table)
		(ordered-pizza customer-22)
		(waiting-at customer-23 bar)
		(ordered-pizza customer-23)
		(waiting-at customer-24 table)
		(ordered-pizza customer-24)
		(waiting-at customer-25 table)
		(ordered-pizza customer-25)
		(waiting-at customer-26 bar)
		(ordered-pizza customer-26)
		(waiting-at customer-27 table)
		(ordered-pizza customer-27)
		(waiting-at customer-28 table)
		(ordered-pizza customer-28)
		(waiting-at customer-29 bar)
		(ordered-pizza customer-29)
		(waiting-at customer-30 bar)
		(ordered-pizza customer-30)
		(waiting-at customer-31 table)
		(ordered-pizza customer-31)
		(waiting-at customer-32 table)
		(ordered-pizza customer-32)
		(waiting-at customer-33 table)
		(ordered-pizza customer-33)
		(waiting-at customer-34 table)
		(ordered-pizza customer-34)
		(waiting-at customer-35 bar)
		(ordered-pizza customer-35)
		(waiting-at customer-36 table)
		(ordered-pizza customer-36)
		(waiting-at customer-37 bar)
		(ordered-pizza customer-37)
		(waiting-at customer-38 bar)
		(ordered-pizza customer-38)
		(waiting-at customer-39 table)
		(ordered-pizza customer-39)
		(waiting-at customer-40 bar)
		(ordered-pizza customer-40)
		(waiting-at customer-41 table)
		(ordered-pizza customer-41)
		(waiting-at customer-42 table)
		(ordered-pizza customer-42)
		(waiting-at customer-43 table)
		(ordered-pizza customer-43)
		(waiting-at customer-44 bar)
		(ordered-pizza customer-44)
		(waiting-at customer-45 bar)
		(ordered-pizza customer-45)
		(waiting-at customer-46 bar)
		(ordered-pizza customer-46)
		(waiting-at customer-47 table)
		(ordered-pizza customer-47)
		(waiting-at customer-48 table)
		(ordered-pizza customer-48)
		(waiting-at customer-49 table)
		(ordered-pizza customer-49)
		(waiting-at customer-50 table)
		(ordered-pizza customer-50)
		(waiting-at customer-51 bar)
		(ordered-pizza customer-51)
		(waiting-at customer-52 bar)
		(ordered-pizza customer-52)
		(waiting-at customer-53 table)
		(ordered-pizza customer-53)
		(waiting-at customer-54 bar)
		(ordered-pizza customer-54)
		(waiting-at customer-55 table)
		(ordered-pizza customer-55)
		(waiting-at customer-56 bar)
		(ordered-pizza customer-56)
		(waiting-at customer-57 table)
		(ordered-pizza customer-57)
		(waiting-at customer-58 bar)
		(ordered-pizza customer-58)
		(waiting-at customer-59 bar)
		(ordered-pizza customer-59)
		(waiting-at customer-60 table)
		(ordered-fries customer-60)
		(waiting-at customer-61 bar)
		(ordered-fries customer-61)
		(waiting-at customer-62 bar)
		(ordered-fries customer-62)
		(waiting-at customer-63 table)
		(ordered-fries customer-63)
		(waiting-at customer-64 table)
		(ordered-fries customer-64)
		(waiting-at customer-65 bar)
		(ordered-fries customer-65)
		(waiting-at customer-66 table)
		(ordered-fries customer-66)
		(waiting-at customer-67 table)
		(ordered-fries customer-67)
		(waiting-at customer-68 bar)
		(ordered-fries customer-68)
		(waiting-at customer-69 bar)
		(ordered-fries customer-69)
		(waiting-at customer-70 bar)
		(ordered-fries customer-70)
		(waiting-at customer-71 table)
		(ordered-fries customer-71)
		(waiting-at customer-72 bar)
		(ordered-fries customer-72)
		(waiting-at customer-73 table)
		(ordered-fries customer-73)
		(waiting-at customer-74 table)
		(ordered-fries customer-74)
		(waiting-at customer-75 bar)
		(ordered-fries customer-75)
		(waiting-at customer-76 bar)
		(ordered-fries customer-76)
		(waiting-at customer-77 bar)
		(ordered-fries customer-77)
		(waiting-at customer-78 bar)
		(ordered-fries customer-78)
		(waiting-at customer-79 table)
		(ordered-fries customer-79)
		(waiting-at customer-80 table)
		(ordered-fries customer-80)
		(waiting-at customer-81 bar)
		(ordered-fries customer-81)
		(waiting-at customer-82 table)
		(ordered-fries customer-82)
		(waiting-at customer-83 table)
		(ordered-fries customer-83)
		(waiting-at customer-84 table)
		(ordered-fries customer-84)
		(waiting-at customer-85 table)
		(ordered-fries customer-85)
		(waiting-at customer-86 table)
		(ordered-fries customer-86)
		(waiting-at customer-87 bar)
		(ordered-fries customer-87)
		(waiting-at customer-88 table)
		(ordered-fries customer-88)
		(waiting-at customer-89 table)
		(ordered-fries customer-89)
		(waiting-at customer-90 bar)
		(ordered-fries customer-90)
		(waiting-at customer-91 bar)
		(ordered-fries customer-91)
		(waiting-at customer-92 bar)
		(ordered-fries customer-92)
		(waiting-at customer-93 bar)
		(ordered-fries customer-93)
		(waiting-at customer-94 bar)
		(ordered-fries customer-94)
		(waiting-at customer-95 table)
		(ordered-fries customer-95)
		(waiting-at customer-96 table)
		(ordered-fries customer-96)
		(waiting-at customer-97 table)
		(ordered-fries customer-97)
		(waiting-at customer-98 bar)
		(ordered-fries customer-98)
		(waiting-at customer-99 bar)
		(ordered-fries customer-99)
		(waiting-at customer-100 bar)
		(ordered-fries customer-100)
		(at server-1 kitchen)
		(empty-hand server-1)
		(at dough-1 kitchen)
		(at dough-2 kitchen)
		(at dough-3 kitchen)
		(at dough-4 kitchen)
		(at dough-5 kitchen)
		(at dough-6 kitchen)
		(at dough-7 kitchen)
		(at dough-8 kitchen)
		(at dough-9 kitchen)
		(at dough-10 kitchen)
		(at dough-11 kitchen)
		(at dough-12 kitchen)
		(at dough-13 kitchen)
		(at dough-14 kitchen)
		(at dough-15 kitchen)
		(at dough-16 kitchen)
		(at dough-17 kitchen)
		(at dough-18 kitchen)
		(at dough-19 kitchen)
		(at dough-20 kitchen)
		(at dough-21 kitchen)
		(at dough-22 kitchen)
		(at dough-23 kitchen)
		(at dough-24 kitchen)
		(at dough-25 kitchen)
		(at dough-26 kitchen)
		(at dough-27 kitchen)
		(at dough-28 kitchen)
		(at dough-29 kitchen)
		(at dough-30 kitchen)
		(at dough-31 kitchen)
		(at dough-32 kitchen)
		(at dough-33 kitchen)
		(at dough-34 kitchen)
		(at dough-35 kitchen)
		(at dough-36 kitchen)
		(at dough-37 kitchen)
		(at dough-38 kitchen)
		(at dough-39 kitchen)
		(at dough-40 kitchen)
		(at dough-41 kitchen)
		(at dough-42 kitchen)
		(at dough-43 kitchen)
		(at dough-44 kitchen)
		(at dough-45 kitchen)
		(at dough-46 kitchen)
		(at dough-47 kitchen)
		(at dough-48 kitchen)
		(at dough-49 kitchen)
		(at dough-50 kitchen)
		(at dough-51 kitchen)
		(at dough-52 kitchen)
		(at dough-53 kitchen)
		(at dough-54 kitchen)
		(at dough-55 kitchen)
		(at dough-56 kitchen)
		(at dough-57 kitchen)
		(at dough-58 kitchen)
		(at dough-59 kitchen)
		(at toppings-1 kitchen)
		(at toppings-2 kitchen)
		(at toppings-3 kitchen)
		(at toppings-4 kitchen)
		(at toppings-5 kitchen)
		(at toppings-6 kitchen)
		(at toppings-7 kitchen)
		(at toppings-8 kitchen)
		(at toppings-9 kitchen)
		(at toppings-10 kitchen)
		(at toppings-11 kitchen)
		(at toppings-12 kitchen)
		(at toppings-13 kitchen)
		(at toppings-14 kitchen)
		(at toppings-15 kitchen)
		(at toppings-16 kitchen)
		(at toppings-17 kitchen)
		(at toppings-18 kitchen)
		(at toppings-19 kitchen)
		(at toppings-20 kitchen)
		(at toppings-21 kitchen)
		(at toppings-22 kitchen)
		(at toppings-23 kitchen)
		(at toppings-24 kitchen)
		(at toppings-25 kitchen)
		(at toppings-26 kitchen)
		(at toppings-27 kitchen)
		(at toppings-28 kitchen)
		(at toppings-29 kitchen)
		(at toppings-30 kitchen)
		(at toppings-31 kitchen)
		(at toppings-32 kitchen)
		(at toppings-33 kitchen)
		(at toppings-34 kitchen)
		(at toppings-35 kitchen)
		(at toppings-36 kitchen)
		(at toppings-37 kitchen)
		(at toppings-38 kitchen)
		(at toppings-39 kitchen)
		(at toppings-40 kitchen)
		(at toppings-41 kitchen)
		(at toppings-42 kitchen)
		(at toppings-43 kitchen)
		(at toppings-44 kitchen)
		(at toppings-45 kitchen)
		(at toppings-46 kitchen)
		(at toppings-47 kitchen)
		(at toppings-48 kitchen)
		(at toppings-49 kitchen)
		(at toppings-50 kitchen)
		(at toppings-51 kitchen)
		(at toppings-52 kitchen)
		(at toppings-53 kitchen)
		(at toppings-54 kitchen)
		(at toppings-55 kitchen)
		(at toppings-56 kitchen)
		(at toppings-57 kitchen)
		(at toppings-58 kitchen)
		(at toppings-59 kitchen)
		(at cheese-1 kitchen)
		(at cheese-2 kitchen)
		(at cheese-3 kitchen)
		(at cheese-4 kitchen)
		(at cheese-5 kitchen)
		(at cheese-6 kitchen)
		(at cheese-7 kitchen)
		(at cheese-8 kitchen)
		(at cheese-9 kitchen)
		(at cheese-10 kitchen)
		(at cheese-11 kitchen)
		(at cheese-12 kitchen)
		(at cheese-13 kitchen)
		(at cheese-14 kitchen)
		(at cheese-15 kitchen)
		(at cheese-16 kitchen)
		(at cheese-17 kitchen)
		(at cheese-18 kitchen)
		(at cheese-19 kitchen)
		(at cheese-20 kitchen)
		(at cheese-21 kitchen)
		(at cheese-22 kitchen)
		(at cheese-23 kitchen)
		(at cheese-24 kitchen)
		(at cheese-25 kitchen)
		(at cheese-26 kitchen)
		(at cheese-27 kitchen)
		(at cheese-28 kitchen)
		(at cheese-29 kitchen)
		(at cheese-30 kitchen)
		(at cheese-31 kitchen)
		(at cheese-32 kitchen)
		(at cheese-33 kitchen)
		(at cheese-34 kitchen)
		(at cheese-35 kitchen)
		(at cheese-36 kitchen)
		(at cheese-37 kitchen)
		(at cheese-38 kitchen)
		(at cheese-39 kitchen)
		(at cheese-40 kitchen)
		(at cheese-41 kitchen)
		(at cheese-42 kitchen)
		(at cheese-43 kitchen)
		(at cheese-44 kitchen)
		(at cheese-45 kitchen)
		(at cheese-46 kitchen)
		(at cheese-47 kitchen)
		(at cheese-48 kitchen)
		(at cheese-49 kitchen)
		(at cheese-50 kitchen)
		(at cheese-51 kitchen)
		(at cheese-52 kitchen)
		(at cheese-53 kitchen)
		(at cheese-54 kitchen)
		(at cheese-55 kitchen)
		(at cheese-56 kitchen)
		(at cheese-57 kitchen)
		(at cheese-58 kitchen)
		(at cheese-59 kitchen)
		(at potato-1 kitchen)
		(at potato-2 kitchen)
		(at potato-3 kitchen)
		(at potato-4 kitchen)
		(at potato-5 kitchen)
		(at potato-6 kitchen)
		(at potato-7 kitchen)
		(at potato-8 kitchen)
		(at potato-9 kitchen)
		(at potato-10 kitchen)
		(at potato-11 kitchen)
		(at potato-12 kitchen)
		(at potato-13 kitchen)
		(at potato-14 kitchen)
		(at potato-15 kitchen)
		(at potato-16 kitchen)
		(at potato-17 kitchen)
		(at potato-18 kitchen)
		(at potato-19 kitchen)
		(at potato-20 kitchen)
		(at potato-21 kitchen)
		(at potato-22 kitchen)
		(at potato-23 kitchen)
		(at potato-24 kitchen)
		(at potato-25 kitchen)
		(at potato-26 kitchen)
		(at potato-27 kitchen)
		(at potato-28 kitchen)
		(at potato-29 kitchen)
		(at potato-30 kitchen)
		(at potato-31 kitchen)
		(at potato-32 kitchen)
		(at potato-33 kitchen)
		(at potato-34 kitchen)
		(at potato-35 kitchen)
		(at potato-36 kitchen)
		(at potato-37 kitchen)
		(at potato-38 kitchen)
		(at potato-39 kitchen)
		(at potato-40 kitchen)
		(at potato-41 kitchen)
		(full-potato potato-1)
		(full-potato potato-2)
		(full-potato potato-3)
		(full-potato potato-4)
		(full-potato potato-5)
		(full-potato potato-6)
		(full-potato potato-7)
		(full-potato potato-8)
		(full-potato potato-9)
		(full-potato potato-10)
		(full-potato potato-11)
		(full-potato potato-12)
		(full-potato potato-13)
		(full-potato potato-14)
		(full-potato potato-15)
		(full-potato potato-16)
		(full-potato potato-17)
		(full-potato potato-18)
		(full-potato potato-19)
		(full-potato potato-20)
		(full-potato potato-21)
		(full-potato potato-22)
		(full-potato potato-23)
		(full-potato potato-24)
		(full-potato potato-25)
		(full-potato potato-26)
		(full-potato potato-27)
		(full-potato potato-28)
		(full-potato potato-29)
		(full-potato potato-30)
		(full-potato potato-31)
		(full-potato potato-32)
		(full-potato potato-33)
		(full-potato potato-34)
		(full-potato potato-35)
		(full-potato potato-36)
		(full-potato potato-37)
		(full-potato potato-38)
		(full-potato potato-39)
		(full-potato potato-40)
		(full-potato potato-41)
		(no-exist-pizza pizza-1)
		(no-exist-pizza pizza-2)
		(no-exist-pizza pizza-3)
		(no-exist-pizza pizza-4)
		(no-exist-pizza pizza-5)
		(no-exist-pizza pizza-6)
		(no-exist-pizza pizza-7)
		(no-exist-pizza pizza-8)
		(no-exist-pizza pizza-9)
		(no-exist-pizza pizza-10)
		(no-exist-pizza pizza-11)
		(no-exist-pizza pizza-12)
		(no-exist-pizza pizza-13)
		(no-exist-pizza pizza-14)
		(no-exist-pizza pizza-15)
		(no-exist-pizza pizza-16)
		(no-exist-pizza pizza-17)
		(no-exist-pizza pizza-18)
		(no-exist-pizza pizza-19)
		(no-exist-pizza pizza-20)
		(no-exist-pizza pizza-21)
		(no-exist-pizza pizza-22)
		(no-exist-pizza pizza-23)
		(no-exist-pizza pizza-24)
		(no-exist-pizza pizza-25)
		(no-exist-pizza pizza-26)
		(no-exist-pizza pizza-27)
		(no-exist-pizza pizza-28)
		(no-exist-pizza pizza-29)
		(no-exist-pizza pizza-30)
		(no-exist-pizza pizza-31)
		(no-exist-pizza pizza-32)
		(no-exist-pizza pizza-33)
		(no-exist-pizza pizza-34)
		(no-exist-pizza pizza-35)
		(no-exist-pizza pizza-36)
		(no-exist-pizza pizza-37)
		(no-exist-pizza pizza-38)
		(no-exist-pizza pizza-39)
		(no-exist-pizza pizza-40)
		(no-exist-pizza pizza-41)
		(no-exist-pizza pizza-42)
		(no-exist-pizza pizza-43)
		(no-exist-pizza pizza-44)
		(no-exist-pizza pizza-45)
		(no-exist-pizza pizza-46)
		(no-exist-pizza pizza-47)
		(no-exist-pizza pizza-48)
		(no-exist-pizza pizza-49)
		(no-exist-pizza pizza-50)
		(no-exist-pizza pizza-51)
		(no-exist-pizza pizza-52)
		(no-exist-pizza pizza-53)
		(no-exist-pizza pizza-54)
		(no-exist-pizza pizza-55)
		(no-exist-pizza pizza-56)
		(no-exist-pizza pizza-57)
		(no-exist-pizza pizza-58)
		(no-exist-pizza pizza-59)
		(no-exist-fries fries-1)
		(no-exist-fries fries-2)
		(no-exist-fries fries-3)
		(no-exist-fries fries-4)
		(no-exist-fries fries-5)
		(no-exist-fries fries-6)
		(no-exist-fries fries-7)
		(no-exist-fries fries-8)
		(no-exist-fries fries-9)
		(no-exist-fries fries-10)
		(no-exist-fries fries-11)
		(no-exist-fries fries-12)
		(no-exist-fries fries-13)
		(no-exist-fries fries-14)
		(no-exist-fries fries-15)
		(no-exist-fries fries-16)
		(no-exist-fries fries-17)
		(no-exist-fries fries-18)
		(no-exist-fries fries-19)
		(no-exist-fries fries-20)
		(no-exist-fries fries-21)
		(no-exist-fries fries-22)
		(no-exist-fries fries-23)
		(no-exist-fries fries-24)
		(no-exist-fries fries-25)
		(no-exist-fries fries-26)
		(no-exist-fries fries-27)
		(no-exist-fries fries-28)
		(no-exist-fries fries-29)
		(no-exist-fries fries-30)
		(no-exist-fries fries-31)
		(no-exist-fries fries-32)
		(no-exist-fries fries-33)
		(no-exist-fries fries-34)
		(no-exist-fries fries-35)
		(no-exist-fries fries-36)
		(no-exist-fries fries-37)
		(no-exist-fries fries-38)
		(no-exist-fries fries-39)
		(no-exist-fries fries-40)
		(no-exist-fries fries-41)
	)
	(:goal (and
		(served customer-1)
		(served customer-2)
		(served customer-3)
		(served customer-4)
		(served customer-5)
		(served customer-6)
		(served customer-7)
		(served customer-8)
		(served customer-9)
		(served customer-10)
		(served customer-11)
		(served customer-12)
		(served customer-13)
		(served customer-14)
		(served customer-15)
		(served customer-16)
		(served customer-17)
		(served customer-18)
		(served customer-19)
		(served customer-20)
		(served customer-21)
		(served customer-22)
		(served customer-23)
		(served customer-24)
		(served customer-25)
		(served customer-26)
		(served customer-27)
		(served customer-28)
		(served customer-29)
		(served customer-30)
		(served customer-31)
		(served customer-32)
		(served customer-33)
		(served customer-34)
		(served customer-35)
		(served customer-36)
		(served customer-37)
		(served customer-38)
		(served customer-39)
		(served customer-40)
		(served customer-41)
		(served customer-42)
		(served customer-43)
		(served customer-44)
		(served customer-45)
		(served customer-46)
		(served customer-47)
		(served customer-48)
		(served customer-49)
		(served customer-50)
		(served customer-51)
		(served customer-52)
		(served customer-53)
		(served customer-54)
		(served customer-55)
		(served customer-56)
		(served customer-57)
		(served customer-58)
		(served customer-59)
		(served customer-60)
		(served customer-61)
		(served customer-62)
		(served customer-63)
		(served customer-64)
		(served customer-65)
		(served customer-66)
		(served customer-67)
		(served customer-68)
		(served customer-69)
		(served customer-70)
		(served customer-71)
		(served customer-72)
		(served customer-73)
		(served customer-74)
		(served customer-75)
		(served customer-76)
		(served customer-77)
		(served customer-78)
		(served customer-79)
		(served customer-80)
		(served customer-81)
		(served customer-82)
		(served customer-83)
		(served customer-84)
		(served customer-85)
		(served customer-86)
		(served customer-87)
		(served customer-88)
		(served customer-89)
		(served customer-90)
		(served customer-91)
		(served customer-92)
		(served customer-93)
		(served customer-94)
		(served customer-95)
		(served customer-96)
		(served customer-97)
		(served customer-98)
		(served customer-99)
		(served customer-100)
		)
	)
)
