#!/bin/bash

echo 'Domain = ' $1

RESULT_DIR=~/git/csc494/testing/foo
DOMAINS_DIR=~/git/csc494/domains/

source activate py27

cd $RESULT_DIR

for filename in $DOMAINS_DIR/$1/foo/*.pddl; do
	# echo $filename
	../run-all-planners $DOMAINS_DIR/$1/domain.pddl $filename
done
