#!/bin/bash

echo 'Problem Instance = ' $(basename $2)

RESULT=$(pwd)/$(basename $2 .pddl)-result.txt

source activate py27
echo $2 > $RESULT

source activate py27
cd ~/git/loom

echo "RUNNING LOOM ./generalize"
printf "\n================ ./generalize ===============\n" >> $RESULT
time ./generalize $1 $2 | tail -1 >> $RESULT
printf "\n"

echo "RUNNING LOOM ./solve"
printf "\n================ ./solve ===============\n" >> $RESULT
time ./solve | tail -32 >> $RESULT
printf "\n"
./clean

cd ~/git/downward
./fast-downward.py --cleanup

echo "RUNNING DOWNWARD --translate"
printf "\n================ --translate ===============\n" >> $RESULT
time ./fast-downward.py --translate $2 | tail -3 >> $RESULT
printf "\n"

echo "RUNNING DOWNWARD --alias lama-first"
printf "\n================ --alias lama-first ===============\n" >> $RESULT
time ./fast-downward.py --alias lama-first output.sas | tail -17 >> $RESULT
printf "\n"

./fast-downward.py --cleanup
# LM-CUT - SLOW, OMIT FOR NOW
# echo "RUNNING DOWNWARD --search astar(lmcut())"
# printf "\n================ astar(lmcut()) ===============\n" >> $RESULT
# time timeout 600s ./fast-downward.py $2 --search "astar(lmcut())" | tail -21 >> $RESULT
# printf "\n"

# ./fast-downward.py --cleanup

echo "DONE!"
