(define (problem ytransport-m100-s100)
	(:domain y-transport)
	(:objects
		monitor-1 monitor-2 monitor-3 monitor-4 monitor-5 monitor-6 monitor-7 monitor-8 monitor-9 monitor-10 monitor-11 monitor-12 monitor-13 monitor-14 monitor-15 monitor-16 monitor-17 monitor-18 monitor-19 monitor-20 monitor-21 monitor-22 monitor-23 monitor-24 monitor-25 monitor-26 monitor-27 monitor-28 monitor-29 monitor-30 monitor-31 monitor-32 monitor-33 monitor-34 monitor-35 monitor-36 monitor-37 monitor-38 monitor-39 monitor-40 monitor-41 monitor-42 monitor-43 monitor-44 monitor-45 monitor-46 monitor-47 monitor-48 monitor-49 monitor-50 monitor-51 monitor-52 monitor-53 monitor-54 monitor-55 monitor-56 monitor-57 monitor-58 monitor-59 monitor-60 monitor-61 monitor-62 monitor-63 monitor-64 monitor-65 monitor-66 monitor-67 monitor-68 monitor-69 monitor-70 monitor-71 monitor-72 monitor-73 monitor-74 monitor-75 monitor-76 monitor-77 monitor-78 monitor-79 monitor-80 monitor-81 monitor-82 monitor-83 monitor-84 monitor-85 monitor-86 monitor-87 monitor-88 monitor-89 monitor-90 monitor-91 monitor-92 monitor-93 monitor-94 monitor-95 monitor-96 monitor-97 monitor-98 monitor-99 monitor-100 - package
		server-1 server-2 server-3 server-4 server-5 server-6 server-7 server-8 server-9 server-10 server-11 server-12 server-13 server-14 server-15 server-16 server-17 server-18 server-19 server-20 server-21 server-22 server-23 server-24 server-25 server-26 server-27 server-28 server-29 server-30 server-31 server-32 server-33 server-34 server-35 server-36 server-37 server-38 server-39 server-40 server-41 server-42 server-43 server-44 server-45 server-46 server-47 server-48 server-49 server-50 server-51 server-52 server-53 server-54 server-55 server-56 server-57 server-58 server-59 server-60 server-61 server-62 server-63 server-64 server-65 server-66 server-67 server-68 server-69 server-70 server-71 server-72 server-73 server-74 server-75 server-76 server-77 server-78 server-79 server-80 server-81 server-82 server-83 server-84 server-85 server-86 server-87 server-88 server-89 server-90 server-91 server-92 server-93 server-94 server-95 server-96 server-97 server-98 server-99 server-100 - package
		capacity-0 capacity-1 capacity-2 - capacity-number
	)
	(:init
		(capacity-predecessor capacity-0 capacity-1)
		(capacity-predecessor capacity-1 capacity-2)
		(MONITOR monitor-1)
		(MONITOR monitor-2)
		(MONITOR monitor-3)
		(MONITOR monitor-4)
		(MONITOR monitor-5)
		(MONITOR monitor-6)
		(MONITOR monitor-7)
		(MONITOR monitor-8)
		(MONITOR monitor-9)
		(MONITOR monitor-10)
		(MONITOR monitor-11)
		(MONITOR monitor-12)
		(MONITOR monitor-13)
		(MONITOR monitor-14)
		(MONITOR monitor-15)
		(MONITOR monitor-16)
		(MONITOR monitor-17)
		(MONITOR monitor-18)
		(MONITOR monitor-19)
		(MONITOR monitor-20)
		(MONITOR monitor-21)
		(MONITOR monitor-22)
		(MONITOR monitor-23)
		(MONITOR monitor-24)
		(MONITOR monitor-25)
		(MONITOR monitor-26)
		(MONITOR monitor-27)
		(MONITOR monitor-28)
		(MONITOR monitor-29)
		(MONITOR monitor-30)
		(MONITOR monitor-31)
		(MONITOR monitor-32)
		(MONITOR monitor-33)
		(MONITOR monitor-34)
		(MONITOR monitor-35)
		(MONITOR monitor-36)
		(MONITOR monitor-37)
		(MONITOR monitor-38)
		(MONITOR monitor-39)
		(MONITOR monitor-40)
		(MONITOR monitor-41)
		(MONITOR monitor-42)
		(MONITOR monitor-43)
		(MONITOR monitor-44)
		(MONITOR monitor-45)
		(MONITOR monitor-46)
		(MONITOR monitor-47)
		(MONITOR monitor-48)
		(MONITOR monitor-49)
		(MONITOR monitor-50)
		(MONITOR monitor-51)
		(MONITOR monitor-52)
		(MONITOR monitor-53)
		(MONITOR monitor-54)
		(MONITOR monitor-55)
		(MONITOR monitor-56)
		(MONITOR monitor-57)
		(MONITOR monitor-58)
		(MONITOR monitor-59)
		(MONITOR monitor-60)
		(MONITOR monitor-61)
		(MONITOR monitor-62)
		(MONITOR monitor-63)
		(MONITOR monitor-64)
		(MONITOR monitor-65)
		(MONITOR monitor-66)
		(MONITOR monitor-67)
		(MONITOR monitor-68)
		(MONITOR monitor-69)
		(MONITOR monitor-70)
		(MONITOR monitor-71)
		(MONITOR monitor-72)
		(MONITOR monitor-73)
		(MONITOR monitor-74)
		(MONITOR monitor-75)
		(MONITOR monitor-76)
		(MONITOR monitor-77)
		(MONITOR monitor-78)
		(MONITOR monitor-79)
		(MONITOR monitor-80)
		(MONITOR monitor-81)
		(MONITOR monitor-82)
		(MONITOR monitor-83)
		(MONITOR monitor-84)
		(MONITOR monitor-85)
		(MONITOR monitor-86)
		(MONITOR monitor-87)
		(MONITOR monitor-88)
		(MONITOR monitor-89)
		(MONITOR monitor-90)
		(MONITOR monitor-91)
		(MONITOR monitor-92)
		(MONITOR monitor-93)
		(MONITOR monitor-94)
		(MONITOR monitor-95)
		(MONITOR monitor-96)
		(MONITOR monitor-97)
		(MONITOR monitor-98)
		(MONITOR monitor-99)
		(MONITOR monitor-100)
		(SERVER server-1)
		(SERVER server-2)
		(SERVER server-3)
		(SERVER server-4)
		(SERVER server-5)
		(SERVER server-6)
		(SERVER server-7)
		(SERVER server-8)
		(SERVER server-9)
		(SERVER server-10)
		(SERVER server-11)
		(SERVER server-12)
		(SERVER server-13)
		(SERVER server-14)
		(SERVER server-15)
		(SERVER server-16)
		(SERVER server-17)
		(SERVER server-18)
		(SERVER server-19)
		(SERVER server-20)
		(SERVER server-21)
		(SERVER server-22)
		(SERVER server-23)
		(SERVER server-24)
		(SERVER server-25)
		(SERVER server-26)
		(SERVER server-27)
		(SERVER server-28)
		(SERVER server-29)
		(SERVER server-30)
		(SERVER server-31)
		(SERVER server-32)
		(SERVER server-33)
		(SERVER server-34)
		(SERVER server-35)
		(SERVER server-36)
		(SERVER server-37)
		(SERVER server-38)
		(SERVER server-39)
		(SERVER server-40)
		(SERVER server-41)
		(SERVER server-42)
		(SERVER server-43)
		(SERVER server-44)
		(SERVER server-45)
		(SERVER server-46)
		(SERVER server-47)
		(SERVER server-48)
		(SERVER server-49)
		(SERVER server-50)
		(SERVER server-51)
		(SERVER server-52)
		(SERVER server-53)
		(SERVER server-54)
		(SERVER server-55)
		(SERVER server-56)
		(SERVER server-57)
		(SERVER server-58)
		(SERVER server-59)
		(SERVER server-60)
		(SERVER server-61)
		(SERVER server-62)
		(SERVER server-63)
		(SERVER server-64)
		(SERVER server-65)
		(SERVER server-66)
		(SERVER server-67)
		(SERVER server-68)
		(SERVER server-69)
		(SERVER server-70)
		(SERVER server-71)
		(SERVER server-72)
		(SERVER server-73)
		(SERVER server-74)
		(SERVER server-75)
		(SERVER server-76)
		(SERVER server-77)
		(SERVER server-78)
		(SERVER server-79)
		(SERVER server-80)
		(SERVER server-81)
		(SERVER server-82)
		(SERVER server-83)
		(SERVER server-84)
		(SERVER server-85)
		(SERVER server-86)
		(SERVER server-87)
		(SERVER server-88)
		(SERVER server-89)
		(SERVER server-90)
		(SERVER server-91)
		(SERVER server-92)
		(SERVER server-93)
		(SERVER server-94)
		(SERVER server-95)
		(SERVER server-96)
		(SERVER server-97)
		(SERVER server-98)
		(SERVER server-99)
		(SERVER server-100)
		(road temp-loc monitor-loc)
		(road monitor-loc temp-loc)
		(road temp-loc server-loc)
		(road server-loc temp-loc)
		(road temp-loc goal-loc)
		(road goal-loc temp-loc)
		(at monitor-1 monitor-loc)
		(at monitor-2 monitor-loc)
		(at monitor-3 monitor-loc)
		(at monitor-4 monitor-loc)
		(at monitor-5 monitor-loc)
		(at monitor-6 monitor-loc)
		(at monitor-7 monitor-loc)
		(at monitor-8 monitor-loc)
		(at monitor-9 monitor-loc)
		(at monitor-10 monitor-loc)
		(at monitor-11 monitor-loc)
		(at monitor-12 monitor-loc)
		(at monitor-13 monitor-loc)
		(at monitor-14 monitor-loc)
		(at monitor-15 monitor-loc)
		(at monitor-16 monitor-loc)
		(at monitor-17 monitor-loc)
		(at monitor-18 monitor-loc)
		(at monitor-19 monitor-loc)
		(at monitor-20 monitor-loc)
		(at monitor-21 monitor-loc)
		(at monitor-22 monitor-loc)
		(at monitor-23 monitor-loc)
		(at monitor-24 monitor-loc)
		(at monitor-25 monitor-loc)
		(at monitor-26 monitor-loc)
		(at monitor-27 monitor-loc)
		(at monitor-28 monitor-loc)
		(at monitor-29 monitor-loc)
		(at monitor-30 monitor-loc)
		(at monitor-31 monitor-loc)
		(at monitor-32 monitor-loc)
		(at monitor-33 monitor-loc)
		(at monitor-34 monitor-loc)
		(at monitor-35 monitor-loc)
		(at monitor-36 monitor-loc)
		(at monitor-37 monitor-loc)
		(at monitor-38 monitor-loc)
		(at monitor-39 monitor-loc)
		(at monitor-40 monitor-loc)
		(at monitor-41 monitor-loc)
		(at monitor-42 monitor-loc)
		(at monitor-43 monitor-loc)
		(at monitor-44 monitor-loc)
		(at monitor-45 monitor-loc)
		(at monitor-46 monitor-loc)
		(at monitor-47 monitor-loc)
		(at monitor-48 monitor-loc)
		(at monitor-49 monitor-loc)
		(at monitor-50 monitor-loc)
		(at monitor-51 monitor-loc)
		(at monitor-52 monitor-loc)
		(at monitor-53 monitor-loc)
		(at monitor-54 monitor-loc)
		(at monitor-55 monitor-loc)
		(at monitor-56 monitor-loc)
		(at monitor-57 monitor-loc)
		(at monitor-58 monitor-loc)
		(at monitor-59 monitor-loc)
		(at monitor-60 monitor-loc)
		(at monitor-61 monitor-loc)
		(at monitor-62 monitor-loc)
		(at monitor-63 monitor-loc)
		(at monitor-64 monitor-loc)
		(at monitor-65 monitor-loc)
		(at monitor-66 monitor-loc)
		(at monitor-67 monitor-loc)
		(at monitor-68 monitor-loc)
		(at monitor-69 monitor-loc)
		(at monitor-70 monitor-loc)
		(at monitor-71 monitor-loc)
		(at monitor-72 monitor-loc)
		(at monitor-73 monitor-loc)
		(at monitor-74 monitor-loc)
		(at monitor-75 monitor-loc)
		(at monitor-76 monitor-loc)
		(at monitor-77 monitor-loc)
		(at monitor-78 monitor-loc)
		(at monitor-79 monitor-loc)
		(at monitor-80 monitor-loc)
		(at monitor-81 monitor-loc)
		(at monitor-82 monitor-loc)
		(at monitor-83 monitor-loc)
		(at monitor-84 monitor-loc)
		(at monitor-85 monitor-loc)
		(at monitor-86 monitor-loc)
		(at monitor-87 monitor-loc)
		(at monitor-88 monitor-loc)
		(at monitor-89 monitor-loc)
		(at monitor-90 monitor-loc)
		(at monitor-91 monitor-loc)
		(at monitor-92 monitor-loc)
		(at monitor-93 monitor-loc)
		(at monitor-94 monitor-loc)
		(at monitor-95 monitor-loc)
		(at monitor-96 monitor-loc)
		(at monitor-97 monitor-loc)
		(at monitor-98 monitor-loc)
		(at monitor-99 monitor-loc)
		(at monitor-100 monitor-loc)
		(at server-1 server-loc)
		(at server-2 server-loc)
		(at server-3 server-loc)
		(at server-4 server-loc)
		(at server-5 server-loc)
		(at server-6 server-loc)
		(at server-7 server-loc)
		(at server-8 server-loc)
		(at server-9 server-loc)
		(at server-10 server-loc)
		(at server-11 server-loc)
		(at server-12 server-loc)
		(at server-13 server-loc)
		(at server-14 server-loc)
		(at server-15 server-loc)
		(at server-16 server-loc)
		(at server-17 server-loc)
		(at server-18 server-loc)
		(at server-19 server-loc)
		(at server-20 server-loc)
		(at server-21 server-loc)
		(at server-22 server-loc)
		(at server-23 server-loc)
		(at server-24 server-loc)
		(at server-25 server-loc)
		(at server-26 server-loc)
		(at server-27 server-loc)
		(at server-28 server-loc)
		(at server-29 server-loc)
		(at server-30 server-loc)
		(at server-31 server-loc)
		(at server-32 server-loc)
		(at server-33 server-loc)
		(at server-34 server-loc)
		(at server-35 server-loc)
		(at server-36 server-loc)
		(at server-37 server-loc)
		(at server-38 server-loc)
		(at server-39 server-loc)
		(at server-40 server-loc)
		(at server-41 server-loc)
		(at server-42 server-loc)
		(at server-43 server-loc)
		(at server-44 server-loc)
		(at server-45 server-loc)
		(at server-46 server-loc)
		(at server-47 server-loc)
		(at server-48 server-loc)
		(at server-49 server-loc)
		(at server-50 server-loc)
		(at server-51 server-loc)
		(at server-52 server-loc)
		(at server-53 server-loc)
		(at server-54 server-loc)
		(at server-55 server-loc)
		(at server-56 server-loc)
		(at server-57 server-loc)
		(at server-58 server-loc)
		(at server-59 server-loc)
		(at server-60 server-loc)
		(at server-61 server-loc)
		(at server-62 server-loc)
		(at server-63 server-loc)
		(at server-64 server-loc)
		(at server-65 server-loc)
		(at server-66 server-loc)
		(at server-67 server-loc)
		(at server-68 server-loc)
		(at server-69 server-loc)
		(at server-70 server-loc)
		(at server-71 server-loc)
		(at server-72 server-loc)
		(at server-73 server-loc)
		(at server-74 server-loc)
		(at server-75 server-loc)
		(at server-76 server-loc)
		(at server-77 server-loc)
		(at server-78 server-loc)
		(at server-79 server-loc)
		(at server-80 server-loc)
		(at server-81 server-loc)
		(at server-82 server-loc)
		(at server-83 server-loc)
		(at server-84 server-loc)
		(at server-85 server-loc)
		(at server-86 server-loc)
		(at server-87 server-loc)
		(at server-88 server-loc)
		(at server-89 server-loc)
		(at server-90 server-loc)
		(at server-91 server-loc)
		(at server-92 server-loc)
		(at server-93 server-loc)
		(at server-94 server-loc)
		(at server-95 server-loc)
		(at server-96 server-loc)
		(at server-97 server-loc)
		(at server-98 server-loc)
		(at server-99 server-loc)
		(at server-100 server-loc)
		(at truck-1 temp-loc)
		(at truck-2 temp-loc)
		(capacity truck-1 capacity-1)
		(capacity truck-2 capacity-2)
		(goal goal-loc)
		(no-goal monitor-loc)
		(no-goal server-loc)
		(no-goal temp-loc)
	)
	(:goal (and
		(at monitor-1 goal-loc)
		(at monitor-2 goal-loc)
		(at monitor-3 goal-loc)
		(at monitor-4 goal-loc)
		(at monitor-5 goal-loc)
		(at monitor-6 goal-loc)
		(at monitor-7 goal-loc)
		(at monitor-8 goal-loc)
		(at monitor-9 goal-loc)
		(at monitor-10 goal-loc)
		(at monitor-11 goal-loc)
		(at monitor-12 goal-loc)
		(at monitor-13 goal-loc)
		(at monitor-14 goal-loc)
		(at monitor-15 goal-loc)
		(at monitor-16 goal-loc)
		(at monitor-17 goal-loc)
		(at monitor-18 goal-loc)
		(at monitor-19 goal-loc)
		(at monitor-20 goal-loc)
		(at monitor-21 goal-loc)
		(at monitor-22 goal-loc)
		(at monitor-23 goal-loc)
		(at monitor-24 goal-loc)
		(at monitor-25 goal-loc)
		(at monitor-26 goal-loc)
		(at monitor-27 goal-loc)
		(at monitor-28 goal-loc)
		(at monitor-29 goal-loc)
		(at monitor-30 goal-loc)
		(at monitor-31 goal-loc)
		(at monitor-32 goal-loc)
		(at monitor-33 goal-loc)
		(at monitor-34 goal-loc)
		(at monitor-35 goal-loc)
		(at monitor-36 goal-loc)
		(at monitor-37 goal-loc)
		(at monitor-38 goal-loc)
		(at monitor-39 goal-loc)
		(at monitor-40 goal-loc)
		(at monitor-41 goal-loc)
		(at monitor-42 goal-loc)
		(at monitor-43 goal-loc)
		(at monitor-44 goal-loc)
		(at monitor-45 goal-loc)
		(at monitor-46 goal-loc)
		(at monitor-47 goal-loc)
		(at monitor-48 goal-loc)
		(at monitor-49 goal-loc)
		(at monitor-50 goal-loc)
		(at monitor-51 goal-loc)
		(at monitor-52 goal-loc)
		(at monitor-53 goal-loc)
		(at monitor-54 goal-loc)
		(at monitor-55 goal-loc)
		(at monitor-56 goal-loc)
		(at monitor-57 goal-loc)
		(at monitor-58 goal-loc)
		(at monitor-59 goal-loc)
		(at monitor-60 goal-loc)
		(at monitor-61 goal-loc)
		(at monitor-62 goal-loc)
		(at monitor-63 goal-loc)
		(at monitor-64 goal-loc)
		(at monitor-65 goal-loc)
		(at monitor-66 goal-loc)
		(at monitor-67 goal-loc)
		(at monitor-68 goal-loc)
		(at monitor-69 goal-loc)
		(at monitor-70 goal-loc)
		(at monitor-71 goal-loc)
		(at monitor-72 goal-loc)
		(at monitor-73 goal-loc)
		(at monitor-74 goal-loc)
		(at monitor-75 goal-loc)
		(at monitor-76 goal-loc)
		(at monitor-77 goal-loc)
		(at monitor-78 goal-loc)
		(at monitor-79 goal-loc)
		(at monitor-80 goal-loc)
		(at monitor-81 goal-loc)
		(at monitor-82 goal-loc)
		(at monitor-83 goal-loc)
		(at monitor-84 goal-loc)
		(at monitor-85 goal-loc)
		(at monitor-86 goal-loc)
		(at monitor-87 goal-loc)
		(at monitor-88 goal-loc)
		(at monitor-89 goal-loc)
		(at monitor-90 goal-loc)
		(at monitor-91 goal-loc)
		(at monitor-92 goal-loc)
		(at monitor-93 goal-loc)
		(at monitor-94 goal-loc)
		(at monitor-95 goal-loc)
		(at monitor-96 goal-loc)
		(at monitor-97 goal-loc)
		(at monitor-98 goal-loc)
		(at monitor-99 goal-loc)
		(at monitor-100 goal-loc)
		(at server-1 goal-loc)
		(at server-2 goal-loc)
		(at server-3 goal-loc)
		(at server-4 goal-loc)
		(at server-5 goal-loc)
		(at server-6 goal-loc)
		(at server-7 goal-loc)
		(at server-8 goal-loc)
		(at server-9 goal-loc)
		(at server-10 goal-loc)
		(at server-11 goal-loc)
		(at server-12 goal-loc)
		(at server-13 goal-loc)
		(at server-14 goal-loc)
		(at server-15 goal-loc)
		(at server-16 goal-loc)
		(at server-17 goal-loc)
		(at server-18 goal-loc)
		(at server-19 goal-loc)
		(at server-20 goal-loc)
		(at server-21 goal-loc)
		(at server-22 goal-loc)
		(at server-23 goal-loc)
		(at server-24 goal-loc)
		(at server-25 goal-loc)
		(at server-26 goal-loc)
		(at server-27 goal-loc)
		(at server-28 goal-loc)
		(at server-29 goal-loc)
		(at server-30 goal-loc)
		(at server-31 goal-loc)
		(at server-32 goal-loc)
		(at server-33 goal-loc)
		(at server-34 goal-loc)
		(at server-35 goal-loc)
		(at server-36 goal-loc)
		(at server-37 goal-loc)
		(at server-38 goal-loc)
		(at server-39 goal-loc)
		(at server-40 goal-loc)
		(at server-41 goal-loc)
		(at server-42 goal-loc)
		(at server-43 goal-loc)
		(at server-44 goal-loc)
		(at server-45 goal-loc)
		(at server-46 goal-loc)
		(at server-47 goal-loc)
		(at server-48 goal-loc)
		(at server-49 goal-loc)
		(at server-50 goal-loc)
		(at server-51 goal-loc)
		(at server-52 goal-loc)
		(at server-53 goal-loc)
		(at server-54 goal-loc)
		(at server-55 goal-loc)
		(at server-56 goal-loc)
		(at server-57 goal-loc)
		(at server-58 goal-loc)
		(at server-59 goal-loc)
		(at server-60 goal-loc)
		(at server-61 goal-loc)
		(at server-62 goal-loc)
		(at server-63 goal-loc)
		(at server-64 goal-loc)
		(at server-65 goal-loc)
		(at server-66 goal-loc)
		(at server-67 goal-loc)
		(at server-68 goal-loc)
		(at server-69 goal-loc)
		(at server-70 goal-loc)
		(at server-71 goal-loc)
		(at server-72 goal-loc)
		(at server-73 goal-loc)
		(at server-74 goal-loc)
		(at server-75 goal-loc)
		(at server-76 goal-loc)
		(at server-77 goal-loc)
		(at server-78 goal-loc)
		(at server-79 goal-loc)
		(at server-80 goal-loc)
		(at server-81 goal-loc)
		(at server-82 goal-loc)
		(at server-83 goal-loc)
		(at server-84 goal-loc)
		(at server-85 goal-loc)
		(at server-86 goal-loc)
		(at server-87 goal-loc)
		(at server-88 goal-loc)
		(at server-89 goal-loc)
		(at server-90 goal-loc)
		(at server-91 goal-loc)
		(at server-92 goal-loc)
		(at server-93 goal-loc)
		(at server-94 goal-loc)
		(at server-95 goal-loc)
		(at server-96 goal-loc)
		(at server-97 goal-loc)
		(at server-98 goal-loc)
		(at server-99 goal-loc)
		(at server-100 goal-loc)
		)
	)
)
