(define (problem ytransport-m10-s10)
	(:domain y-transport)
	(:objects
		monitor-1 monitor-2 monitor-3 monitor-4 monitor-5 monitor-6 monitor-7 monitor-8 monitor-9 monitor-10 - package
		server-1 server-2 server-3 server-4 server-5 server-6 server-7 server-8 server-9 server-10 - package
		capacity-0 capacity-1 capacity-2 - capacity-number
	)
	(:init
		(capacity-predecessor capacity-0 capacity-1)
		(capacity-predecessor capacity-1 capacity-2)
		(MONITOR monitor-1)
		(MONITOR monitor-2)
		(MONITOR monitor-3)
		(MONITOR monitor-4)
		(MONITOR monitor-5)
		(MONITOR monitor-6)
		(MONITOR monitor-7)
		(MONITOR monitor-8)
		(MONITOR monitor-9)
		(MONITOR monitor-10)
		(SERVER server-1)
		(SERVER server-2)
		(SERVER server-3)
		(SERVER server-4)
		(SERVER server-5)
		(SERVER server-6)
		(SERVER server-7)
		(SERVER server-8)
		(SERVER server-9)
		(SERVER server-10)
		(road temp-loc monitor-loc)
		(road monitor-loc temp-loc)
		(road temp-loc server-loc)
		(road server-loc temp-loc)
		(road temp-loc goal-loc)
		(road goal-loc temp-loc)
		(at monitor-1 monitor-loc)
		(at monitor-2 monitor-loc)
		(at monitor-3 monitor-loc)
		(at monitor-4 monitor-loc)
		(at monitor-5 monitor-loc)
		(at monitor-6 monitor-loc)
		(at monitor-7 monitor-loc)
		(at monitor-8 monitor-loc)
		(at monitor-9 monitor-loc)
		(at monitor-10 monitor-loc)
		(at server-1 server-loc)
		(at server-2 server-loc)
		(at server-3 server-loc)
		(at server-4 server-loc)
		(at server-5 server-loc)
		(at server-6 server-loc)
		(at server-7 server-loc)
		(at server-8 server-loc)
		(at server-9 server-loc)
		(at server-10 server-loc)
		(at truck-1 temp-loc)
		(at truck-2 temp-loc)
		(capacity truck-1 capacity-1)
		(capacity truck-2 capacity-2)
		(goal goal-loc)
		(no-goal monitor-loc)
		(no-goal server-loc)
		(no-goal temp-loc)
	)
	(:goal (and
		(at monitor-1 goal-loc)
		(at monitor-2 goal-loc)
		(at monitor-3 goal-loc)
		(at monitor-4 goal-loc)
		(at monitor-5 goal-loc)
		(at monitor-6 goal-loc)
		(at monitor-7 goal-loc)
		(at monitor-8 goal-loc)
		(at monitor-9 goal-loc)
		(at monitor-10 goal-loc)
		(at server-1 goal-loc)
		(at server-2 goal-loc)
		(at server-3 goal-loc)
		(at server-4 goal-loc)
		(at server-5 goal-loc)
		(at server-6 goal-loc)
		(at server-7 goal-loc)
		(at server-8 goal-loc)
		(at server-9 goal-loc)
		(at server-10 goal-loc)
		)
	)
)
