(define (problem construction-t1-c100-w1)
	(:domain construction)
	(:objects
		worker-1 - worker
		truck-1 - truck
		wood-part-1 wood-part-2 wood-part-3 wood-part-4 wood-part-5 wood-part-6 wood-part-7 wood-part-8 wood-part-9 wood-part-10 wood-part-11 wood-part-12 wood-part-13 wood-part-14 wood-part-15 wood-part-16 wood-part-17 wood-part-18 wood-part-19 wood-part-20 wood-part-21 wood-part-22 wood-part-23 wood-part-24 wood-part-25 wood-part-26 wood-part-27 wood-part-28 wood-part-29 wood-part-30 wood-part-31 wood-part-32 wood-part-33 wood-part-34 wood-part-35 wood-part-36 wood-part-37 wood-part-38 wood-part-39 wood-part-40 wood-part-41 wood-part-42 wood-part-43 wood-part-44 wood-part-45 wood-part-46 wood-part-47 wood-part-48 wood-part-49 wood-part-50 wood-part-51 wood-part-52 wood-part-53 wood-part-54 wood-part-55 wood-part-56 wood-part-57 wood-part-58 wood-part-59 wood-part-60 wood-part-61 wood-part-62 wood-part-63 wood-part-64 wood-part-65 wood-part-66 wood-part-67 wood-part-68 wood-part-69 wood-part-70 wood-part-71 wood-part-72 wood-part-73 wood-part-74 wood-part-75 wood-part-76 wood-part-77 wood-part-78 wood-part-79 wood-part-80 wood-part-81 wood-part-82 wood-part-83 wood-part-84 wood-part-85 wood-part-86 wood-part-87 wood-part-88 wood-part-89 wood-part-90 wood-part-91 wood-part-92 wood-part-93 wood-part-94 wood-part-95 wood-part-96 wood-part-97 wood-part-98 wood-part-99 wood-part-100 - part
		glass-part-1 glass-part-2 glass-part-3 glass-part-4 glass-part-5 glass-part-6 glass-part-7 glass-part-8 glass-part-9 glass-part-10 glass-part-11 glass-part-12 glass-part-13 glass-part-14 glass-part-15 glass-part-16 glass-part-17 glass-part-18 glass-part-19 glass-part-20 glass-part-21 glass-part-22 glass-part-23 glass-part-24 glass-part-25 glass-part-26 glass-part-27 glass-part-28 glass-part-29 glass-part-30 glass-part-31 glass-part-32 glass-part-33 glass-part-34 glass-part-35 glass-part-36 glass-part-37 glass-part-38 glass-part-39 glass-part-40 glass-part-41 glass-part-42 glass-part-43 glass-part-44 glass-part-45 glass-part-46 glass-part-47 glass-part-48 glass-part-49 glass-part-50 glass-part-51 glass-part-52 glass-part-53 glass-part-54 glass-part-55 glass-part-56 glass-part-57 glass-part-58 glass-part-59 glass-part-60 glass-part-61 glass-part-62 glass-part-63 glass-part-64 glass-part-65 glass-part-66 glass-part-67 glass-part-68 glass-part-69 glass-part-70 glass-part-71 glass-part-72 glass-part-73 glass-part-74 glass-part-75 glass-part-76 glass-part-77 glass-part-78 glass-part-79 glass-part-80 glass-part-81 glass-part-82 glass-part-83 glass-part-84 glass-part-85 glass-part-86 glass-part-87 glass-part-88 glass-part-89 glass-part-90 glass-part-91 glass-part-92 glass-part-93 glass-part-94 glass-part-95 glass-part-96 glass-part-97 glass-part-98 glass-part-99 glass-part-100 - part
		clay-part-1 clay-part-2 clay-part-3 clay-part-4 clay-part-5 clay-part-6 clay-part-7 clay-part-8 clay-part-9 clay-part-10 clay-part-11 clay-part-12 clay-part-13 clay-part-14 clay-part-15 clay-part-16 clay-part-17 clay-part-18 clay-part-19 clay-part-20 clay-part-21 clay-part-22 clay-part-23 clay-part-24 clay-part-25 clay-part-26 clay-part-27 clay-part-28 clay-part-29 clay-part-30 clay-part-31 clay-part-32 clay-part-33 clay-part-34 clay-part-35 clay-part-36 clay-part-37 clay-part-38 clay-part-39 clay-part-40 clay-part-41 clay-part-42 clay-part-43 clay-part-44 clay-part-45 clay-part-46 clay-part-47 clay-part-48 clay-part-49 clay-part-50 clay-part-51 clay-part-52 clay-part-53 clay-part-54 clay-part-55 clay-part-56 clay-part-57 clay-part-58 clay-part-59 clay-part-60 clay-part-61 clay-part-62 clay-part-63 clay-part-64 clay-part-65 clay-part-66 clay-part-67 clay-part-68 clay-part-69 clay-part-70 clay-part-71 clay-part-72 clay-part-73 clay-part-74 clay-part-75 clay-part-76 clay-part-77 clay-part-78 clay-part-79 clay-part-80 clay-part-81 clay-part-82 clay-part-83 clay-part-84 clay-part-85 clay-part-86 clay-part-87 clay-part-88 clay-part-89 clay-part-90 clay-part-91 clay-part-92 clay-part-93 clay-part-94 clay-part-95 clay-part-96 clay-part-97 clay-part-98 clay-part-99 clay-part-100 - part
		composite-1 composite-2 composite-3 composite-4 composite-5 composite-6 composite-7 composite-8 composite-9 composite-10 composite-11 composite-12 composite-13 composite-14 composite-15 composite-16 composite-17 composite-18 composite-19 composite-20 composite-21 composite-22 composite-23 composite-24 composite-25 composite-26 composite-27 composite-28 composite-29 composite-30 composite-31 composite-32 composite-33 composite-34 composite-35 composite-36 composite-37 composite-38 composite-39 composite-40 composite-41 composite-42 composite-43 composite-44 composite-45 composite-46 composite-47 composite-48 composite-49 composite-50 composite-51 composite-52 composite-53 composite-54 composite-55 composite-56 composite-57 composite-58 composite-59 composite-60 composite-61 composite-62 composite-63 composite-64 composite-65 composite-66 composite-67 composite-68 composite-69 composite-70 composite-71 composite-72 composite-73 composite-74 composite-75 composite-76 composite-77 composite-78 composite-79 composite-80 composite-81 composite-82 composite-83 composite-84 composite-85 composite-86 composite-87 composite-88 composite-89 composite-90 composite-91 composite-92 composite-93 composite-94 composite-95 composite-96 composite-97 composite-98 composite-99 composite-100 - composite
		capacity-0 capacity-1 - capacity-number
		wood-warehouse glass-warehouse clay-warehouse construction-area - location
	)
	(:init
		(WOOD wood-part-1)
		(WOOD wood-part-2)
		(WOOD wood-part-3)
		(WOOD wood-part-4)
		(WOOD wood-part-5)
		(WOOD wood-part-6)
		(WOOD wood-part-7)
		(WOOD wood-part-8)
		(WOOD wood-part-9)
		(WOOD wood-part-10)
		(WOOD wood-part-11)
		(WOOD wood-part-12)
		(WOOD wood-part-13)
		(WOOD wood-part-14)
		(WOOD wood-part-15)
		(WOOD wood-part-16)
		(WOOD wood-part-17)
		(WOOD wood-part-18)
		(WOOD wood-part-19)
		(WOOD wood-part-20)
		(WOOD wood-part-21)
		(WOOD wood-part-22)
		(WOOD wood-part-23)
		(WOOD wood-part-24)
		(WOOD wood-part-25)
		(WOOD wood-part-26)
		(WOOD wood-part-27)
		(WOOD wood-part-28)
		(WOOD wood-part-29)
		(WOOD wood-part-30)
		(WOOD wood-part-31)
		(WOOD wood-part-32)
		(WOOD wood-part-33)
		(WOOD wood-part-34)
		(WOOD wood-part-35)
		(WOOD wood-part-36)
		(WOOD wood-part-37)
		(WOOD wood-part-38)
		(WOOD wood-part-39)
		(WOOD wood-part-40)
		(WOOD wood-part-41)
		(WOOD wood-part-42)
		(WOOD wood-part-43)
		(WOOD wood-part-44)
		(WOOD wood-part-45)
		(WOOD wood-part-46)
		(WOOD wood-part-47)
		(WOOD wood-part-48)
		(WOOD wood-part-49)
		(WOOD wood-part-50)
		(WOOD wood-part-51)
		(WOOD wood-part-52)
		(WOOD wood-part-53)
		(WOOD wood-part-54)
		(WOOD wood-part-55)
		(WOOD wood-part-56)
		(WOOD wood-part-57)
		(WOOD wood-part-58)
		(WOOD wood-part-59)
		(WOOD wood-part-60)
		(WOOD wood-part-61)
		(WOOD wood-part-62)
		(WOOD wood-part-63)
		(WOOD wood-part-64)
		(WOOD wood-part-65)
		(WOOD wood-part-66)
		(WOOD wood-part-67)
		(WOOD wood-part-68)
		(WOOD wood-part-69)
		(WOOD wood-part-70)
		(WOOD wood-part-71)
		(WOOD wood-part-72)
		(WOOD wood-part-73)
		(WOOD wood-part-74)
		(WOOD wood-part-75)
		(WOOD wood-part-76)
		(WOOD wood-part-77)
		(WOOD wood-part-78)
		(WOOD wood-part-79)
		(WOOD wood-part-80)
		(WOOD wood-part-81)
		(WOOD wood-part-82)
		(WOOD wood-part-83)
		(WOOD wood-part-84)
		(WOOD wood-part-85)
		(WOOD wood-part-86)
		(WOOD wood-part-87)
		(WOOD wood-part-88)
		(WOOD wood-part-89)
		(WOOD wood-part-90)
		(WOOD wood-part-91)
		(WOOD wood-part-92)
		(WOOD wood-part-93)
		(WOOD wood-part-94)
		(WOOD wood-part-95)
		(WOOD wood-part-96)
		(WOOD wood-part-97)
		(WOOD wood-part-98)
		(WOOD wood-part-99)
		(WOOD wood-part-100)
		(GLASS glass-part-1)
		(GLASS glass-part-2)
		(GLASS glass-part-3)
		(GLASS glass-part-4)
		(GLASS glass-part-5)
		(GLASS glass-part-6)
		(GLASS glass-part-7)
		(GLASS glass-part-8)
		(GLASS glass-part-9)
		(GLASS glass-part-10)
		(GLASS glass-part-11)
		(GLASS glass-part-12)
		(GLASS glass-part-13)
		(GLASS glass-part-14)
		(GLASS glass-part-15)
		(GLASS glass-part-16)
		(GLASS glass-part-17)
		(GLASS glass-part-18)
		(GLASS glass-part-19)
		(GLASS glass-part-20)
		(GLASS glass-part-21)
		(GLASS glass-part-22)
		(GLASS glass-part-23)
		(GLASS glass-part-24)
		(GLASS glass-part-25)
		(GLASS glass-part-26)
		(GLASS glass-part-27)
		(GLASS glass-part-28)
		(GLASS glass-part-29)
		(GLASS glass-part-30)
		(GLASS glass-part-31)
		(GLASS glass-part-32)
		(GLASS glass-part-33)
		(GLASS glass-part-34)
		(GLASS glass-part-35)
		(GLASS glass-part-36)
		(GLASS glass-part-37)
		(GLASS glass-part-38)
		(GLASS glass-part-39)
		(GLASS glass-part-40)
		(GLASS glass-part-41)
		(GLASS glass-part-42)
		(GLASS glass-part-43)
		(GLASS glass-part-44)
		(GLASS glass-part-45)
		(GLASS glass-part-46)
		(GLASS glass-part-47)
		(GLASS glass-part-48)
		(GLASS glass-part-49)
		(GLASS glass-part-50)
		(GLASS glass-part-51)
		(GLASS glass-part-52)
		(GLASS glass-part-53)
		(GLASS glass-part-54)
		(GLASS glass-part-55)
		(GLASS glass-part-56)
		(GLASS glass-part-57)
		(GLASS glass-part-58)
		(GLASS glass-part-59)
		(GLASS glass-part-60)
		(GLASS glass-part-61)
		(GLASS glass-part-62)
		(GLASS glass-part-63)
		(GLASS glass-part-64)
		(GLASS glass-part-65)
		(GLASS glass-part-66)
		(GLASS glass-part-67)
		(GLASS glass-part-68)
		(GLASS glass-part-69)
		(GLASS glass-part-70)
		(GLASS glass-part-71)
		(GLASS glass-part-72)
		(GLASS glass-part-73)
		(GLASS glass-part-74)
		(GLASS glass-part-75)
		(GLASS glass-part-76)
		(GLASS glass-part-77)
		(GLASS glass-part-78)
		(GLASS glass-part-79)
		(GLASS glass-part-80)
		(GLASS glass-part-81)
		(GLASS glass-part-82)
		(GLASS glass-part-83)
		(GLASS glass-part-84)
		(GLASS glass-part-85)
		(GLASS glass-part-86)
		(GLASS glass-part-87)
		(GLASS glass-part-88)
		(GLASS glass-part-89)
		(GLASS glass-part-90)
		(GLASS glass-part-91)
		(GLASS glass-part-92)
		(GLASS glass-part-93)
		(GLASS glass-part-94)
		(GLASS glass-part-95)
		(GLASS glass-part-96)
		(GLASS glass-part-97)
		(GLASS glass-part-98)
		(GLASS glass-part-99)
		(GLASS glass-part-100)
		(CLAY clay-part-1)
		(CLAY clay-part-2)
		(CLAY clay-part-3)
		(CLAY clay-part-4)
		(CLAY clay-part-5)
		(CLAY clay-part-6)
		(CLAY clay-part-7)
		(CLAY clay-part-8)
		(CLAY clay-part-9)
		(CLAY clay-part-10)
		(CLAY clay-part-11)
		(CLAY clay-part-12)
		(CLAY clay-part-13)
		(CLAY clay-part-14)
		(CLAY clay-part-15)
		(CLAY clay-part-16)
		(CLAY clay-part-17)
		(CLAY clay-part-18)
		(CLAY clay-part-19)
		(CLAY clay-part-20)
		(CLAY clay-part-21)
		(CLAY clay-part-22)
		(CLAY clay-part-23)
		(CLAY clay-part-24)
		(CLAY clay-part-25)
		(CLAY clay-part-26)
		(CLAY clay-part-27)
		(CLAY clay-part-28)
		(CLAY clay-part-29)
		(CLAY clay-part-30)
		(CLAY clay-part-31)
		(CLAY clay-part-32)
		(CLAY clay-part-33)
		(CLAY clay-part-34)
		(CLAY clay-part-35)
		(CLAY clay-part-36)
		(CLAY clay-part-37)
		(CLAY clay-part-38)
		(CLAY clay-part-39)
		(CLAY clay-part-40)
		(CLAY clay-part-41)
		(CLAY clay-part-42)
		(CLAY clay-part-43)
		(CLAY clay-part-44)
		(CLAY clay-part-45)
		(CLAY clay-part-46)
		(CLAY clay-part-47)
		(CLAY clay-part-48)
		(CLAY clay-part-49)
		(CLAY clay-part-50)
		(CLAY clay-part-51)
		(CLAY clay-part-52)
		(CLAY clay-part-53)
		(CLAY clay-part-54)
		(CLAY clay-part-55)
		(CLAY clay-part-56)
		(CLAY clay-part-57)
		(CLAY clay-part-58)
		(CLAY clay-part-59)
		(CLAY clay-part-60)
		(CLAY clay-part-61)
		(CLAY clay-part-62)
		(CLAY clay-part-63)
		(CLAY clay-part-64)
		(CLAY clay-part-65)
		(CLAY clay-part-66)
		(CLAY clay-part-67)
		(CLAY clay-part-68)
		(CLAY clay-part-69)
		(CLAY clay-part-70)
		(CLAY clay-part-71)
		(CLAY clay-part-72)
		(CLAY clay-part-73)
		(CLAY clay-part-74)
		(CLAY clay-part-75)
		(CLAY clay-part-76)
		(CLAY clay-part-77)
		(CLAY clay-part-78)
		(CLAY clay-part-79)
		(CLAY clay-part-80)
		(CLAY clay-part-81)
		(CLAY clay-part-82)
		(CLAY clay-part-83)
		(CLAY clay-part-84)
		(CLAY clay-part-85)
		(CLAY clay-part-86)
		(CLAY clay-part-87)
		(CLAY clay-part-88)
		(CLAY clay-part-89)
		(CLAY clay-part-90)
		(CLAY clay-part-91)
		(CLAY clay-part-92)
		(CLAY clay-part-93)
		(CLAY clay-part-94)
		(CLAY clay-part-95)
		(CLAY clay-part-96)
		(CLAY clay-part-97)
		(CLAY clay-part-98)
		(CLAY clay-part-99)
		(CLAY clay-part-100)
		(at worker-1 construction-area)
		(at truck-1 construction-area)
		(at wood-part-1 wood-warehouse)
		(at wood-part-2 wood-warehouse)
		(at wood-part-3 wood-warehouse)
		(at wood-part-4 wood-warehouse)
		(at wood-part-5 wood-warehouse)
		(at wood-part-6 wood-warehouse)
		(at wood-part-7 wood-warehouse)
		(at wood-part-8 wood-warehouse)
		(at wood-part-9 wood-warehouse)
		(at wood-part-10 wood-warehouse)
		(at wood-part-11 wood-warehouse)
		(at wood-part-12 wood-warehouse)
		(at wood-part-13 wood-warehouse)
		(at wood-part-14 wood-warehouse)
		(at wood-part-15 wood-warehouse)
		(at wood-part-16 wood-warehouse)
		(at wood-part-17 wood-warehouse)
		(at wood-part-18 wood-warehouse)
		(at wood-part-19 wood-warehouse)
		(at wood-part-20 wood-warehouse)
		(at wood-part-21 wood-warehouse)
		(at wood-part-22 wood-warehouse)
		(at wood-part-23 wood-warehouse)
		(at wood-part-24 wood-warehouse)
		(at wood-part-25 wood-warehouse)
		(at wood-part-26 wood-warehouse)
		(at wood-part-27 wood-warehouse)
		(at wood-part-28 wood-warehouse)
		(at wood-part-29 wood-warehouse)
		(at wood-part-30 wood-warehouse)
		(at wood-part-31 wood-warehouse)
		(at wood-part-32 wood-warehouse)
		(at wood-part-33 wood-warehouse)
		(at wood-part-34 wood-warehouse)
		(at wood-part-35 wood-warehouse)
		(at wood-part-36 wood-warehouse)
		(at wood-part-37 wood-warehouse)
		(at wood-part-38 wood-warehouse)
		(at wood-part-39 wood-warehouse)
		(at wood-part-40 wood-warehouse)
		(at wood-part-41 wood-warehouse)
		(at wood-part-42 wood-warehouse)
		(at wood-part-43 wood-warehouse)
		(at wood-part-44 wood-warehouse)
		(at wood-part-45 wood-warehouse)
		(at wood-part-46 wood-warehouse)
		(at wood-part-47 wood-warehouse)
		(at wood-part-48 wood-warehouse)
		(at wood-part-49 wood-warehouse)
		(at wood-part-50 wood-warehouse)
		(at wood-part-51 wood-warehouse)
		(at wood-part-52 wood-warehouse)
		(at wood-part-53 wood-warehouse)
		(at wood-part-54 wood-warehouse)
		(at wood-part-55 wood-warehouse)
		(at wood-part-56 wood-warehouse)
		(at wood-part-57 wood-warehouse)
		(at wood-part-58 wood-warehouse)
		(at wood-part-59 wood-warehouse)
		(at wood-part-60 wood-warehouse)
		(at wood-part-61 wood-warehouse)
		(at wood-part-62 wood-warehouse)
		(at wood-part-63 wood-warehouse)
		(at wood-part-64 wood-warehouse)
		(at wood-part-65 wood-warehouse)
		(at wood-part-66 wood-warehouse)
		(at wood-part-67 wood-warehouse)
		(at wood-part-68 wood-warehouse)
		(at wood-part-69 wood-warehouse)
		(at wood-part-70 wood-warehouse)
		(at wood-part-71 wood-warehouse)
		(at wood-part-72 wood-warehouse)
		(at wood-part-73 wood-warehouse)
		(at wood-part-74 wood-warehouse)
		(at wood-part-75 wood-warehouse)
		(at wood-part-76 wood-warehouse)
		(at wood-part-77 wood-warehouse)
		(at wood-part-78 wood-warehouse)
		(at wood-part-79 wood-warehouse)
		(at wood-part-80 wood-warehouse)
		(at wood-part-81 wood-warehouse)
		(at wood-part-82 wood-warehouse)
		(at wood-part-83 wood-warehouse)
		(at wood-part-84 wood-warehouse)
		(at wood-part-85 wood-warehouse)
		(at wood-part-86 wood-warehouse)
		(at wood-part-87 wood-warehouse)
		(at wood-part-88 wood-warehouse)
		(at wood-part-89 wood-warehouse)
		(at wood-part-90 wood-warehouse)
		(at wood-part-91 wood-warehouse)
		(at wood-part-92 wood-warehouse)
		(at wood-part-93 wood-warehouse)
		(at wood-part-94 wood-warehouse)
		(at wood-part-95 wood-warehouse)
		(at wood-part-96 wood-warehouse)
		(at wood-part-97 wood-warehouse)
		(at wood-part-98 wood-warehouse)
		(at wood-part-99 wood-warehouse)
		(at wood-part-100 wood-warehouse)
		(at glass-part-1 glass-warehouse)
		(at glass-part-2 glass-warehouse)
		(at glass-part-3 glass-warehouse)
		(at glass-part-4 glass-warehouse)
		(at glass-part-5 glass-warehouse)
		(at glass-part-6 glass-warehouse)
		(at glass-part-7 glass-warehouse)
		(at glass-part-8 glass-warehouse)
		(at glass-part-9 glass-warehouse)
		(at glass-part-10 glass-warehouse)
		(at glass-part-11 glass-warehouse)
		(at glass-part-12 glass-warehouse)
		(at glass-part-13 glass-warehouse)
		(at glass-part-14 glass-warehouse)
		(at glass-part-15 glass-warehouse)
		(at glass-part-16 glass-warehouse)
		(at glass-part-17 glass-warehouse)
		(at glass-part-18 glass-warehouse)
		(at glass-part-19 glass-warehouse)
		(at glass-part-20 glass-warehouse)
		(at glass-part-21 glass-warehouse)
		(at glass-part-22 glass-warehouse)
		(at glass-part-23 glass-warehouse)
		(at glass-part-24 glass-warehouse)
		(at glass-part-25 glass-warehouse)
		(at glass-part-26 glass-warehouse)
		(at glass-part-27 glass-warehouse)
		(at glass-part-28 glass-warehouse)
		(at glass-part-29 glass-warehouse)
		(at glass-part-30 glass-warehouse)
		(at glass-part-31 glass-warehouse)
		(at glass-part-32 glass-warehouse)
		(at glass-part-33 glass-warehouse)
		(at glass-part-34 glass-warehouse)
		(at glass-part-35 glass-warehouse)
		(at glass-part-36 glass-warehouse)
		(at glass-part-37 glass-warehouse)
		(at glass-part-38 glass-warehouse)
		(at glass-part-39 glass-warehouse)
		(at glass-part-40 glass-warehouse)
		(at glass-part-41 glass-warehouse)
		(at glass-part-42 glass-warehouse)
		(at glass-part-43 glass-warehouse)
		(at glass-part-44 glass-warehouse)
		(at glass-part-45 glass-warehouse)
		(at glass-part-46 glass-warehouse)
		(at glass-part-47 glass-warehouse)
		(at glass-part-48 glass-warehouse)
		(at glass-part-49 glass-warehouse)
		(at glass-part-50 glass-warehouse)
		(at glass-part-51 glass-warehouse)
		(at glass-part-52 glass-warehouse)
		(at glass-part-53 glass-warehouse)
		(at glass-part-54 glass-warehouse)
		(at glass-part-55 glass-warehouse)
		(at glass-part-56 glass-warehouse)
		(at glass-part-57 glass-warehouse)
		(at glass-part-58 glass-warehouse)
		(at glass-part-59 glass-warehouse)
		(at glass-part-60 glass-warehouse)
		(at glass-part-61 glass-warehouse)
		(at glass-part-62 glass-warehouse)
		(at glass-part-63 glass-warehouse)
		(at glass-part-64 glass-warehouse)
		(at glass-part-65 glass-warehouse)
		(at glass-part-66 glass-warehouse)
		(at glass-part-67 glass-warehouse)
		(at glass-part-68 glass-warehouse)
		(at glass-part-69 glass-warehouse)
		(at glass-part-70 glass-warehouse)
		(at glass-part-71 glass-warehouse)
		(at glass-part-72 glass-warehouse)
		(at glass-part-73 glass-warehouse)
		(at glass-part-74 glass-warehouse)
		(at glass-part-75 glass-warehouse)
		(at glass-part-76 glass-warehouse)
		(at glass-part-77 glass-warehouse)
		(at glass-part-78 glass-warehouse)
		(at glass-part-79 glass-warehouse)
		(at glass-part-80 glass-warehouse)
		(at glass-part-81 glass-warehouse)
		(at glass-part-82 glass-warehouse)
		(at glass-part-83 glass-warehouse)
		(at glass-part-84 glass-warehouse)
		(at glass-part-85 glass-warehouse)
		(at glass-part-86 glass-warehouse)
		(at glass-part-87 glass-warehouse)
		(at glass-part-88 glass-warehouse)
		(at glass-part-89 glass-warehouse)
		(at glass-part-90 glass-warehouse)
		(at glass-part-91 glass-warehouse)
		(at glass-part-92 glass-warehouse)
		(at glass-part-93 glass-warehouse)
		(at glass-part-94 glass-warehouse)
		(at glass-part-95 glass-warehouse)
		(at glass-part-96 glass-warehouse)
		(at glass-part-97 glass-warehouse)
		(at glass-part-98 glass-warehouse)
		(at glass-part-99 glass-warehouse)
		(at glass-part-100 glass-warehouse)
		(at clay-part-1 clay-warehouse)
		(at clay-part-2 clay-warehouse)
		(at clay-part-3 clay-warehouse)
		(at clay-part-4 clay-warehouse)
		(at clay-part-5 clay-warehouse)
		(at clay-part-6 clay-warehouse)
		(at clay-part-7 clay-warehouse)
		(at clay-part-8 clay-warehouse)
		(at clay-part-9 clay-warehouse)
		(at clay-part-10 clay-warehouse)
		(at clay-part-11 clay-warehouse)
		(at clay-part-12 clay-warehouse)
		(at clay-part-13 clay-warehouse)
		(at clay-part-14 clay-warehouse)
		(at clay-part-15 clay-warehouse)
		(at clay-part-16 clay-warehouse)
		(at clay-part-17 clay-warehouse)
		(at clay-part-18 clay-warehouse)
		(at clay-part-19 clay-warehouse)
		(at clay-part-20 clay-warehouse)
		(at clay-part-21 clay-warehouse)
		(at clay-part-22 clay-warehouse)
		(at clay-part-23 clay-warehouse)
		(at clay-part-24 clay-warehouse)
		(at clay-part-25 clay-warehouse)
		(at clay-part-26 clay-warehouse)
		(at clay-part-27 clay-warehouse)
		(at clay-part-28 clay-warehouse)
		(at clay-part-29 clay-warehouse)
		(at clay-part-30 clay-warehouse)
		(at clay-part-31 clay-warehouse)
		(at clay-part-32 clay-warehouse)
		(at clay-part-33 clay-warehouse)
		(at clay-part-34 clay-warehouse)
		(at clay-part-35 clay-warehouse)
		(at clay-part-36 clay-warehouse)
		(at clay-part-37 clay-warehouse)
		(at clay-part-38 clay-warehouse)
		(at clay-part-39 clay-warehouse)
		(at clay-part-40 clay-warehouse)
		(at clay-part-41 clay-warehouse)
		(at clay-part-42 clay-warehouse)
		(at clay-part-43 clay-warehouse)
		(at clay-part-44 clay-warehouse)
		(at clay-part-45 clay-warehouse)
		(at clay-part-46 clay-warehouse)
		(at clay-part-47 clay-warehouse)
		(at clay-part-48 clay-warehouse)
		(at clay-part-49 clay-warehouse)
		(at clay-part-50 clay-warehouse)
		(at clay-part-51 clay-warehouse)
		(at clay-part-52 clay-warehouse)
		(at clay-part-53 clay-warehouse)
		(at clay-part-54 clay-warehouse)
		(at clay-part-55 clay-warehouse)
		(at clay-part-56 clay-warehouse)
		(at clay-part-57 clay-warehouse)
		(at clay-part-58 clay-warehouse)
		(at clay-part-59 clay-warehouse)
		(at clay-part-60 clay-warehouse)
		(at clay-part-61 clay-warehouse)
		(at clay-part-62 clay-warehouse)
		(at clay-part-63 clay-warehouse)
		(at clay-part-64 clay-warehouse)
		(at clay-part-65 clay-warehouse)
		(at clay-part-66 clay-warehouse)
		(at clay-part-67 clay-warehouse)
		(at clay-part-68 clay-warehouse)
		(at clay-part-69 clay-warehouse)
		(at clay-part-70 clay-warehouse)
		(at clay-part-71 clay-warehouse)
		(at clay-part-72 clay-warehouse)
		(at clay-part-73 clay-warehouse)
		(at clay-part-74 clay-warehouse)
		(at clay-part-75 clay-warehouse)
		(at clay-part-76 clay-warehouse)
		(at clay-part-77 clay-warehouse)
		(at clay-part-78 clay-warehouse)
		(at clay-part-79 clay-warehouse)
		(at clay-part-80 clay-warehouse)
		(at clay-part-81 clay-warehouse)
		(at clay-part-82 clay-warehouse)
		(at clay-part-83 clay-warehouse)
		(at clay-part-84 clay-warehouse)
		(at clay-part-85 clay-warehouse)
		(at clay-part-86 clay-warehouse)
		(at clay-part-87 clay-warehouse)
		(at clay-part-88 clay-warehouse)
		(at clay-part-89 clay-warehouse)
		(at clay-part-90 clay-warehouse)
		(at clay-part-91 clay-warehouse)
		(at clay-part-92 clay-warehouse)
		(at clay-part-93 clay-warehouse)
		(at clay-part-94 clay-warehouse)
		(at clay-part-95 clay-warehouse)
		(at clay-part-96 clay-warehouse)
		(at clay-part-97 clay-warehouse)
		(at clay-part-98 clay-warehouse)
		(at clay-part-99 clay-warehouse)
		(at clay-part-100 clay-warehouse)
		(at composite-1 construction-area)
		(at composite-2 construction-area)
		(at composite-3 construction-area)
		(at composite-4 construction-area)
		(at composite-5 construction-area)
		(at composite-6 construction-area)
		(at composite-7 construction-area)
		(at composite-8 construction-area)
		(at composite-9 construction-area)
		(at composite-10 construction-area)
		(at composite-11 construction-area)
		(at composite-12 construction-area)
		(at composite-13 construction-area)
		(at composite-14 construction-area)
		(at composite-15 construction-area)
		(at composite-16 construction-area)
		(at composite-17 construction-area)
		(at composite-18 construction-area)
		(at composite-19 construction-area)
		(at composite-20 construction-area)
		(at composite-21 construction-area)
		(at composite-22 construction-area)
		(at composite-23 construction-area)
		(at composite-24 construction-area)
		(at composite-25 construction-area)
		(at composite-26 construction-area)
		(at composite-27 construction-area)
		(at composite-28 construction-area)
		(at composite-29 construction-area)
		(at composite-30 construction-area)
		(at composite-31 construction-area)
		(at composite-32 construction-area)
		(at composite-33 construction-area)
		(at composite-34 construction-area)
		(at composite-35 construction-area)
		(at composite-36 construction-area)
		(at composite-37 construction-area)
		(at composite-38 construction-area)
		(at composite-39 construction-area)
		(at composite-40 construction-area)
		(at composite-41 construction-area)
		(at composite-42 construction-area)
		(at composite-43 construction-area)
		(at composite-44 construction-area)
		(at composite-45 construction-area)
		(at composite-46 construction-area)
		(at composite-47 construction-area)
		(at composite-48 construction-area)
		(at composite-49 construction-area)
		(at composite-50 construction-area)
		(at composite-51 construction-area)
		(at composite-52 construction-area)
		(at composite-53 construction-area)
		(at composite-54 construction-area)
		(at composite-55 construction-area)
		(at composite-56 construction-area)
		(at composite-57 construction-area)
		(at composite-58 construction-area)
		(at composite-59 construction-area)
		(at composite-60 construction-area)
		(at composite-61 construction-area)
		(at composite-62 construction-area)
		(at composite-63 construction-area)
		(at composite-64 construction-area)
		(at composite-65 construction-area)
		(at composite-66 construction-area)
		(at composite-67 construction-area)
		(at composite-68 construction-area)
		(at composite-69 construction-area)
		(at composite-70 construction-area)
		(at composite-71 construction-area)
		(at composite-72 construction-area)
		(at composite-73 construction-area)
		(at composite-74 construction-area)
		(at composite-75 construction-area)
		(at composite-76 construction-area)
		(at composite-77 construction-area)
		(at composite-78 construction-area)
		(at composite-79 construction-area)
		(at composite-80 construction-area)
		(at composite-81 construction-area)
		(at composite-82 construction-area)
		(at composite-83 construction-area)
		(at composite-84 construction-area)
		(at composite-85 construction-area)
		(at composite-86 construction-area)
		(at composite-87 construction-area)
		(at composite-88 construction-area)
		(at composite-89 construction-area)
		(at composite-90 construction-area)
		(at composite-91 construction-area)
		(at composite-92 construction-area)
		(at composite-93 construction-area)
		(at composite-94 construction-area)
		(at composite-95 construction-area)
		(at composite-96 construction-area)
		(at composite-97 construction-area)
		(at composite-98 construction-area)
		(at composite-99 construction-area)
		(at composite-100 construction-area)
		(no-driver truck-1)
		(no-assembled composite-1)
		(no-wood composite-1)
		(no-glass composite-1)
		(no-clay composite-1)
		(no-assembled composite-2)
		(no-wood composite-2)
		(no-glass composite-2)
		(no-clay composite-2)
		(no-assembled composite-3)
		(no-wood composite-3)
		(no-glass composite-3)
		(no-clay composite-3)
		(no-assembled composite-4)
		(no-wood composite-4)
		(no-glass composite-4)
		(no-clay composite-4)
		(no-assembled composite-5)
		(no-wood composite-5)
		(no-glass composite-5)
		(no-clay composite-5)
		(no-assembled composite-6)
		(no-wood composite-6)
		(no-glass composite-6)
		(no-clay composite-6)
		(no-assembled composite-7)
		(no-wood composite-7)
		(no-glass composite-7)
		(no-clay composite-7)
		(no-assembled composite-8)
		(no-wood composite-8)
		(no-glass composite-8)
		(no-clay composite-8)
		(no-assembled composite-9)
		(no-wood composite-9)
		(no-glass composite-9)
		(no-clay composite-9)
		(no-assembled composite-10)
		(no-wood composite-10)
		(no-glass composite-10)
		(no-clay composite-10)
		(no-assembled composite-11)
		(no-wood composite-11)
		(no-glass composite-11)
		(no-clay composite-11)
		(no-assembled composite-12)
		(no-wood composite-12)
		(no-glass composite-12)
		(no-clay composite-12)
		(no-assembled composite-13)
		(no-wood composite-13)
		(no-glass composite-13)
		(no-clay composite-13)
		(no-assembled composite-14)
		(no-wood composite-14)
		(no-glass composite-14)
		(no-clay composite-14)
		(no-assembled composite-15)
		(no-wood composite-15)
		(no-glass composite-15)
		(no-clay composite-15)
		(no-assembled composite-16)
		(no-wood composite-16)
		(no-glass composite-16)
		(no-clay composite-16)
		(no-assembled composite-17)
		(no-wood composite-17)
		(no-glass composite-17)
		(no-clay composite-17)
		(no-assembled composite-18)
		(no-wood composite-18)
		(no-glass composite-18)
		(no-clay composite-18)
		(no-assembled composite-19)
		(no-wood composite-19)
		(no-glass composite-19)
		(no-clay composite-19)
		(no-assembled composite-20)
		(no-wood composite-20)
		(no-glass composite-20)
		(no-clay composite-20)
		(no-assembled composite-21)
		(no-wood composite-21)
		(no-glass composite-21)
		(no-clay composite-21)
		(no-assembled composite-22)
		(no-wood composite-22)
		(no-glass composite-22)
		(no-clay composite-22)
		(no-assembled composite-23)
		(no-wood composite-23)
		(no-glass composite-23)
		(no-clay composite-23)
		(no-assembled composite-24)
		(no-wood composite-24)
		(no-glass composite-24)
		(no-clay composite-24)
		(no-assembled composite-25)
		(no-wood composite-25)
		(no-glass composite-25)
		(no-clay composite-25)
		(no-assembled composite-26)
		(no-wood composite-26)
		(no-glass composite-26)
		(no-clay composite-26)
		(no-assembled composite-27)
		(no-wood composite-27)
		(no-glass composite-27)
		(no-clay composite-27)
		(no-assembled composite-28)
		(no-wood composite-28)
		(no-glass composite-28)
		(no-clay composite-28)
		(no-assembled composite-29)
		(no-wood composite-29)
		(no-glass composite-29)
		(no-clay composite-29)
		(no-assembled composite-30)
		(no-wood composite-30)
		(no-glass composite-30)
		(no-clay composite-30)
		(no-assembled composite-31)
		(no-wood composite-31)
		(no-glass composite-31)
		(no-clay composite-31)
		(no-assembled composite-32)
		(no-wood composite-32)
		(no-glass composite-32)
		(no-clay composite-32)
		(no-assembled composite-33)
		(no-wood composite-33)
		(no-glass composite-33)
		(no-clay composite-33)
		(no-assembled composite-34)
		(no-wood composite-34)
		(no-glass composite-34)
		(no-clay composite-34)
		(no-assembled composite-35)
		(no-wood composite-35)
		(no-glass composite-35)
		(no-clay composite-35)
		(no-assembled composite-36)
		(no-wood composite-36)
		(no-glass composite-36)
		(no-clay composite-36)
		(no-assembled composite-37)
		(no-wood composite-37)
		(no-glass composite-37)
		(no-clay composite-37)
		(no-assembled composite-38)
		(no-wood composite-38)
		(no-glass composite-38)
		(no-clay composite-38)
		(no-assembled composite-39)
		(no-wood composite-39)
		(no-glass composite-39)
		(no-clay composite-39)
		(no-assembled composite-40)
		(no-wood composite-40)
		(no-glass composite-40)
		(no-clay composite-40)
		(no-assembled composite-41)
		(no-wood composite-41)
		(no-glass composite-41)
		(no-clay composite-41)
		(no-assembled composite-42)
		(no-wood composite-42)
		(no-glass composite-42)
		(no-clay composite-42)
		(no-assembled composite-43)
		(no-wood composite-43)
		(no-glass composite-43)
		(no-clay composite-43)
		(no-assembled composite-44)
		(no-wood composite-44)
		(no-glass composite-44)
		(no-clay composite-44)
		(no-assembled composite-45)
		(no-wood composite-45)
		(no-glass composite-45)
		(no-clay composite-45)
		(no-assembled composite-46)
		(no-wood composite-46)
		(no-glass composite-46)
		(no-clay composite-46)
		(no-assembled composite-47)
		(no-wood composite-47)
		(no-glass composite-47)
		(no-clay composite-47)
		(no-assembled composite-48)
		(no-wood composite-48)
		(no-glass composite-48)
		(no-clay composite-48)
		(no-assembled composite-49)
		(no-wood composite-49)
		(no-glass composite-49)
		(no-clay composite-49)
		(no-assembled composite-50)
		(no-wood composite-50)
		(no-glass composite-50)
		(no-clay composite-50)
		(no-assembled composite-51)
		(no-wood composite-51)
		(no-glass composite-51)
		(no-clay composite-51)
		(no-assembled composite-52)
		(no-wood composite-52)
		(no-glass composite-52)
		(no-clay composite-52)
		(no-assembled composite-53)
		(no-wood composite-53)
		(no-glass composite-53)
		(no-clay composite-53)
		(no-assembled composite-54)
		(no-wood composite-54)
		(no-glass composite-54)
		(no-clay composite-54)
		(no-assembled composite-55)
		(no-wood composite-55)
		(no-glass composite-55)
		(no-clay composite-55)
		(no-assembled composite-56)
		(no-wood composite-56)
		(no-glass composite-56)
		(no-clay composite-56)
		(no-assembled composite-57)
		(no-wood composite-57)
		(no-glass composite-57)
		(no-clay composite-57)
		(no-assembled composite-58)
		(no-wood composite-58)
		(no-glass composite-58)
		(no-clay composite-58)
		(no-assembled composite-59)
		(no-wood composite-59)
		(no-glass composite-59)
		(no-clay composite-59)
		(no-assembled composite-60)
		(no-wood composite-60)
		(no-glass composite-60)
		(no-clay composite-60)
		(no-assembled composite-61)
		(no-wood composite-61)
		(no-glass composite-61)
		(no-clay composite-61)
		(no-assembled composite-62)
		(no-wood composite-62)
		(no-glass composite-62)
		(no-clay composite-62)
		(no-assembled composite-63)
		(no-wood composite-63)
		(no-glass composite-63)
		(no-clay composite-63)
		(no-assembled composite-64)
		(no-wood composite-64)
		(no-glass composite-64)
		(no-clay composite-64)
		(no-assembled composite-65)
		(no-wood composite-65)
		(no-glass composite-65)
		(no-clay composite-65)
		(no-assembled composite-66)
		(no-wood composite-66)
		(no-glass composite-66)
		(no-clay composite-66)
		(no-assembled composite-67)
		(no-wood composite-67)
		(no-glass composite-67)
		(no-clay composite-67)
		(no-assembled composite-68)
		(no-wood composite-68)
		(no-glass composite-68)
		(no-clay composite-68)
		(no-assembled composite-69)
		(no-wood composite-69)
		(no-glass composite-69)
		(no-clay composite-69)
		(no-assembled composite-70)
		(no-wood composite-70)
		(no-glass composite-70)
		(no-clay composite-70)
		(no-assembled composite-71)
		(no-wood composite-71)
		(no-glass composite-71)
		(no-clay composite-71)
		(no-assembled composite-72)
		(no-wood composite-72)
		(no-glass composite-72)
		(no-clay composite-72)
		(no-assembled composite-73)
		(no-wood composite-73)
		(no-glass composite-73)
		(no-clay composite-73)
		(no-assembled composite-74)
		(no-wood composite-74)
		(no-glass composite-74)
		(no-clay composite-74)
		(no-assembled composite-75)
		(no-wood composite-75)
		(no-glass composite-75)
		(no-clay composite-75)
		(no-assembled composite-76)
		(no-wood composite-76)
		(no-glass composite-76)
		(no-clay composite-76)
		(no-assembled composite-77)
		(no-wood composite-77)
		(no-glass composite-77)
		(no-clay composite-77)
		(no-assembled composite-78)
		(no-wood composite-78)
		(no-glass composite-78)
		(no-clay composite-78)
		(no-assembled composite-79)
		(no-wood composite-79)
		(no-glass composite-79)
		(no-clay composite-79)
		(no-assembled composite-80)
		(no-wood composite-80)
		(no-glass composite-80)
		(no-clay composite-80)
		(no-assembled composite-81)
		(no-wood composite-81)
		(no-glass composite-81)
		(no-clay composite-81)
		(no-assembled composite-82)
		(no-wood composite-82)
		(no-glass composite-82)
		(no-clay composite-82)
		(no-assembled composite-83)
		(no-wood composite-83)
		(no-glass composite-83)
		(no-clay composite-83)
		(no-assembled composite-84)
		(no-wood composite-84)
		(no-glass composite-84)
		(no-clay composite-84)
		(no-assembled composite-85)
		(no-wood composite-85)
		(no-glass composite-85)
		(no-clay composite-85)
		(no-assembled composite-86)
		(no-wood composite-86)
		(no-glass composite-86)
		(no-clay composite-86)
		(no-assembled composite-87)
		(no-wood composite-87)
		(no-glass composite-87)
		(no-clay composite-87)
		(no-assembled composite-88)
		(no-wood composite-88)
		(no-glass composite-88)
		(no-clay composite-88)
		(no-assembled composite-89)
		(no-wood composite-89)
		(no-glass composite-89)
		(no-clay composite-89)
		(no-assembled composite-90)
		(no-wood composite-90)
		(no-glass composite-90)
		(no-clay composite-90)
		(no-assembled composite-91)
		(no-wood composite-91)
		(no-glass composite-91)
		(no-clay composite-91)
		(no-assembled composite-92)
		(no-wood composite-92)
		(no-glass composite-92)
		(no-clay composite-92)
		(no-assembled composite-93)
		(no-wood composite-93)
		(no-glass composite-93)
		(no-clay composite-93)
		(no-assembled composite-94)
		(no-wood composite-94)
		(no-glass composite-94)
		(no-clay composite-94)
		(no-assembled composite-95)
		(no-wood composite-95)
		(no-glass composite-95)
		(no-clay composite-95)
		(no-assembled composite-96)
		(no-wood composite-96)
		(no-glass composite-96)
		(no-clay composite-96)
		(no-assembled composite-97)
		(no-wood composite-97)
		(no-glass composite-97)
		(no-clay composite-97)
		(no-assembled composite-98)
		(no-wood composite-98)
		(no-glass composite-98)
		(no-clay composite-98)
		(no-assembled composite-99)
		(no-wood composite-99)
		(no-glass composite-99)
		(no-clay composite-99)
		(no-assembled composite-100)
		(no-wood composite-100)
		(no-glass composite-100)
		(no-clay composite-100)
		(capacity-predecessor capacity-0 capacity-1)
		(capacity truck-1 capacity-1)
	)
	(:goal (and
		(assembled composite-1)
		(assembled composite-2)
		(assembled composite-3)
		(assembled composite-4)
		(assembled composite-5)
		(assembled composite-6)
		(assembled composite-7)
		(assembled composite-8)
		(assembled composite-9)
		(assembled composite-10)
		(assembled composite-11)
		(assembled composite-12)
		(assembled composite-13)
		(assembled composite-14)
		(assembled composite-15)
		(assembled composite-16)
		(assembled composite-17)
		(assembled composite-18)
		(assembled composite-19)
		(assembled composite-20)
		(assembled composite-21)
		(assembled composite-22)
		(assembled composite-23)
		(assembled composite-24)
		(assembled composite-25)
		(assembled composite-26)
		(assembled composite-27)
		(assembled composite-28)
		(assembled composite-29)
		(assembled composite-30)
		(assembled composite-31)
		(assembled composite-32)
		(assembled composite-33)
		(assembled composite-34)
		(assembled composite-35)
		(assembled composite-36)
		(assembled composite-37)
		(assembled composite-38)
		(assembled composite-39)
		(assembled composite-40)
		(assembled composite-41)
		(assembled composite-42)
		(assembled composite-43)
		(assembled composite-44)
		(assembled composite-45)
		(assembled composite-46)
		(assembled composite-47)
		(assembled composite-48)
		(assembled composite-49)
		(assembled composite-50)
		(assembled composite-51)
		(assembled composite-52)
		(assembled composite-53)
		(assembled composite-54)
		(assembled composite-55)
		(assembled composite-56)
		(assembled composite-57)
		(assembled composite-58)
		(assembled composite-59)
		(assembled composite-60)
		(assembled composite-61)
		(assembled composite-62)
		(assembled composite-63)
		(assembled composite-64)
		(assembled composite-65)
		(assembled composite-66)
		(assembled composite-67)
		(assembled composite-68)
		(assembled composite-69)
		(assembled composite-70)
		(assembled composite-71)
		(assembled composite-72)
		(assembled composite-73)
		(assembled composite-74)
		(assembled composite-75)
		(assembled composite-76)
		(assembled composite-77)
		(assembled composite-78)
		(assembled composite-79)
		(assembled composite-80)
		(assembled composite-81)
		(assembled composite-82)
		(assembled composite-83)
		(assembled composite-84)
		(assembled composite-85)
		(assembled composite-86)
		(assembled composite-87)
		(assembled composite-88)
		(assembled composite-89)
		(assembled composite-90)
		(assembled composite-91)
		(assembled composite-92)
		(assembled composite-93)
		(assembled composite-94)
		(assembled composite-95)
		(assembled composite-96)
		(assembled composite-97)
		(assembled composite-98)
		(assembled composite-99)
		(assembled composite-100)
		)
	)
)
