#!/bin/bash

BASEDIR="$(dirname "$0")"

# Specify the basics
planner="~/git/loom"
domain="$BASEDIR"/domain.pddl
problem="$BASEDIR"/problems/p01.pddl

generalizer="~/git/loom/generalize"

# Plan!
echo "$generalizer $domain $problem"
"$generalizer $domain $problem"
