(define (problem cleaning-o10-p10-l10-r1)
	(:domain cleaning)
	(:objects
		organic-1 organic-2 organic-3 organic-4 organic-5 organic-6 organic-7 organic-8 organic-9 organic-10 - organic
		paper-1 paper-2 paper-3 paper-4 paper-5 paper-6 paper-7 paper-8 paper-9 paper-10 - paper
		plastic-1 plastic-2 plastic-3 plastic-4 plastic-5 plastic-6 plastic-7 plastic-8 plastic-9 plastic-10 - plastic
		robot-1 - robot
	)
	(:init
		(on-ground organic-1)
		(on-ground organic-2)
		(on-ground organic-3)
		(on-ground organic-4)
		(on-ground organic-5)
		(on-ground organic-6)
		(on-ground organic-7)
		(on-ground organic-8)
		(on-ground organic-9)
		(on-ground organic-10)
		(on-ground paper-1)
		(on-ground paper-2)
		(on-ground paper-3)
		(on-ground paper-4)
		(on-ground paper-5)
		(on-ground paper-6)
		(on-ground paper-7)
		(on-ground paper-8)
		(on-ground paper-9)
		(on-ground paper-10)
		(on-ground plastic-1)
		(on-ground plastic-2)
		(on-ground plastic-3)
		(on-ground plastic-4)
		(on-ground plastic-5)
		(on-ground plastic-6)
		(on-ground plastic-7)
		(on-ground plastic-8)
		(on-ground plastic-9)
		(on-ground plastic-10)
		(empty-hand robot-1)
	)
	(:goal (and
		(in-compost-bin organic-1)
		(in-compost-bin organic-2)
		(in-compost-bin organic-3)
		(in-compost-bin organic-4)
		(in-compost-bin organic-5)
		(in-compost-bin organic-6)
		(in-compost-bin organic-7)
		(in-compost-bin organic-8)
		(in-compost-bin organic-9)
		(in-compost-bin organic-10)
		(in-plastic-bin plastic-1)
		(in-plastic-bin plastic-2)
		(in-plastic-bin plastic-3)
		(in-plastic-bin plastic-4)
		(in-plastic-bin plastic-5)
		(in-plastic-bin plastic-6)
		(in-plastic-bin plastic-7)
		(in-plastic-bin plastic-8)
		(in-plastic-bin plastic-9)
		(in-plastic-bin plastic-10)
		(in-paper-bin paper-1)
		(in-paper-bin paper-2)
		(in-paper-bin paper-3)
		(in-paper-bin paper-4)
		(in-paper-bin paper-5)
		(in-paper-bin paper-6)
		(in-paper-bin paper-7)
		(in-paper-bin paper-8)
		(in-paper-bin paper-9)
		(in-paper-bin paper-10)
		)
	)
)
